<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?><style type="text/css">
	body{font-family:'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;}
	html{font-family:'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;}
</style>
<script>
    var require = {
        "baseUrl": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('/') ?>"
    };
</script>
