<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


$cart_postcode = '';
if(isset($_COOKIE['cart_postcode'])){
$cart_postcode = $_COOKIE['cart_postcode'];
}


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$checkoutSession = $objectManager->create('Magento\Checkout\Model\Session');

?>
<input type="hidden" id="shippingfullnm" name="shippingfullnm" value="<?php echo $checkoutSession->getQuote()->getShippingAddress()->getFirstName()." ".$checkoutSession->getQuote()->getShippingAddress()->getLastName() ?>">

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('need-help-area')->toHtml();?> 
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified*/  echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>

<script>


function setCookie(cname,cvalue,exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays*24*60*60*1000));
    var expires = "expires=" + d.toGMTString();
    document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}

function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i < ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }
    return "";
}


require([
        'jquery',
        'mage/cookies'
    ], function ($) {
		
		var date = new Date();
		var minutes = 10;
		date.setTime(date.getTime() + (minutes * 60 * 1000));
		
			
		setCookie("chk_psw_val", 0, 30);
				
		jQuery(document).on('focusout', "input[name='password_1']", function(){
			var ht_ml_Encode = window.btoa(jQuery(this).val());
			var ht_ml_Decode = window.atob(ht_ml_Encode);
	       	jQuery.cookie('chk_1', ht_ml_Encode, { path: '/' }, { expires: date });
			
			var chkpsw_val = jQuery(this).val();
			var user=getCookie("chk_psw_val");
			if (chkpsw_val != null && chkpsw_val != '') {
				setCookie("chk_psw_val", 1, 30);
			}else{
				setCookie("chk_psw_val", 0, 30);
			}
				
	
		});
		
		jQuery(document).on('focusout', "#customer-email", function(){
			var user_e = jQuery('#customer-email').val();
			jQuery.cookie('user_e', user_e, { path: '/' }, { expires: date });//Set the cookies
		});
		
		jQuery('body').on('click', '#co-shipping-method-form .button.primary', function() {
		if( jQuery('#shipping-new-address-form div').hasClass('_error')){
		 jQuery('html, body').animate({
		 scrollTop: jQuery(".field._error").offset().top
		 }, 800);
		} else{
		 var inp = jQuery(".form-shipping-address div._required input").val();
		 if (jQuery.trim(inp).length < 1) {
		  jQuery('html, body').animate({
		  scrollTop: jQuery(".field._required").offset().top
		  }, 800);
		 }
		
		if (jQuery(".form-login  input.input-text").hasClass('mage-error')) {
		 jQuery('html, body').animate({
		   scrollTop: jQuery('.form-login').offset().top
		  }, 800);
		}
		}
	   });
});
</script>

<script type="text/javascript">

require(['jquery', 'jquery/ui','mage/url','Magento_Ui/js/block-loader'], function(){
jQuery(document).on('click', '.step-title1', function(){
	jQuery('button.action.action-auth-toggle').trigger('click');
});

jQuery(document).on('click', 'li.opc-progress-bar-item:first', function(){
	jQuery('body').removeClass('second-step');
	jQuery('.store-add1').hide();
});	
	
	jQuery("body").on('DOMSubtreeModified', ".messages", function() {
		
		var myInput = document.getElementById("discount-code");

		if (myInput && myInput.value) {
			jQuery('.action.action-cancel').show();
			jQuery('.action.action-apply').hide();		
		}else{
			jQuery('.action.action-cancel').hide();
			jQuery('.action.action-apply').show();
		}
			
		if (jQuery('div.messages:contains("Coupon code is not valid")').length > 0) {
			jQuery('.action.action-cancel').hide();
			jQuery('.action.action-apply').show();
		}
		
		if (jQuery('div.messages:contains("Your coupon was successfully applied")').length > 0) {
			jQuery('.action.action-cancel').show();
			jQuery('.action.action-apply').hide();	
		}
		
		var postcode = jQuery( "input[name='postcode']" ).val();
		var len = jQuery.trim( jQuery( "input[name='postcode']" ).val()).length;
		if(postcode != '' && len > 3){
			jQuery('span.abt-our-shipp-opt').show(); 	
		}else{
			jQuery('span.abt-our-shipp-opt').hide(); 	
			}

	});
	
	jQuery("body").on('DOMSubtreeModified',"#co-shipping-method-form", function() {
		
		jQuery('span.abt-our-shipp-opt').hide();
		jQuery('.table-checkout-shipping-method p').each(function(){
			if (jQuery(this).text().indexOf('United Parcel Service') > -1) {    
					jQuery('span.abt-our-shipp-opt').show();		
			}
			if (jQuery(this).text().indexOf('Freight Shipping') > -1) {    
					jQuery('span.abt-our-shipp-opt').show();		
			}
			if (jQuery(this).text().indexOf('Local Delivery') > -1) {    
					jQuery('span.abt-our-shipp-opt').show();		
			}
		});		
	});
	
	jQuery("body").on('DOMSubtreeModified',"form.form.form-login", function() {
		setTimeout(function(){	
			if (jQuery('.fieldset.hidden-fields').css('display') == 'none' ) {
				jQuery('div.create-account-ttl').show();
				jQuery("div[name='shippingAddress.password_1']").show();
				jQuery("div[name='shippingAddress.password_2']").show();
				jQuery("div.password-case").show();
				
			}else{
				jQuery('div.create-account-ttl').hide();
				jQuery("div[name='shippingAddress.password_1']").hide();
				jQuery("div[name='shippingAddress.password_2']").hide();
				jQuery("div.password-case").hide();
			}
			
		}, 1000);
	
	});
	
	
	jQuery("body").on('DOMSubtreeModified',"#checkout-step-payment", function() {
		if (jQuery('div.authentication-wrapper').css('display') != 'none' ) {
			jQuery( "#authnetcim-save" ).hide();
			jQuery( "#authnetcim-save" ).parent().find('label').hide();
		}
	});
	
	var shippingmethod = "<?php echo $checkoutSession->getQuote()->getShippingAddress()->getShippingMethod(); ?>";
	jQuery("body").on('DOMSubtreeModified',".opc-block-shipping-information", function() {
		
		if(shippingmethod=="mpcustomshipping_express"){
			if(! jQuery('.store-add1').length ){					
					jQuery('.ship-to .shipping-information-content').hide();
					jQuery('.set-store-address').show();
					jQuery('div.newclass').trigger('click');
			}
		}else{
					jQuery('.ship-to .shipping-information-content').show();
					jQuery('.set-store-address').hide();
			}
		
	});
	
	setTimeout(function(){
        jQuery('div.opc-wrapper,.opc-sidebar.opc-summary-wrapper').wrapAll('<div class="newclass"></div>');
	}, 10000);
	
	



var windowWidth = jQuery(window).width();	
	if(windowWidth > 767){
		jQuery(window).scroll(function () {
		var fixSidebar = jQuery('.page-header').innerHeight();
		var contentHeight = jQuery('.opc-wrapper').innerHeight();
		var sidebarHeight = jQuery('#opc-sidebar').height();
		var sidebarBottomPos = contentHeight - sidebarHeight; 
		var scrolltop = jQuery(window).scrollTop();
		var trigger = scrolltop - fixSidebar;
		var ol_checkoutSteps = jQuery('div.opc-wrapper').height();
		
		
		
		if(ol_checkoutSteps>sidebarHeight){
			if (scrolltop >= fixSidebar) {
				jQuery('#opc-sidebar').addClass('fixed');
					
				var gp_top = scrolltop-150;
				jQuery('#opc-sidebar').css('top','70px');
			} else {
				jQuery('#opc-sidebar').css('top',gp_top+'px');
				jQuery('#opc-sidebar').removeClass('fixed');
			}
		
			var gpcnt = 0;
			contentHeight = contentHeight - sidebarHeight;
			if (trigger >= sidebarBottomPos) {
			
				if(gpcnt == 0){
					jQuery('#opc-sidebar').addClass('bottom');
					jQuery('#opc-sidebar').removeClass('fixed');
					//jQuery('#opc-sidebar').css('top',contentHeight+'px');
					jQuery('#opc-sidebar').css('top','0px');
				}
				gpcnt++;
				
			} else {
				jQuery('#opc-sidebar').removeClass('bottom');
			}
		}
		});

	}

});
</script>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup modal title',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

           
			
		/////////// start
		jQuery('body').on('click', 'span.abt-our-shipp-opt', function() {
			jQuery('span.shipp-name').each(function(){			
				var shipp_name = jQuery(this).text().toLowerCase();
				shipp_name = shipp_name.split(' ').join('-');
				jQuery('#click-'+shipp_name).trigger('click');				
			});

		});
		
		var popup_ups = modal(options, jQuery('#popup-mpdal-united-parcel-service'));
		jQuery("#click-united-parcel-service").on('click',function(){ 
			jQuery("#popup-mpdal-united-parcel-service").modal("openModal");
		});
		
		var popup_freight = modal(options, jQuery('#popup-mpdal-freight-shipping'));
		jQuery("#click-freight-shipping").on('click',function(){ 
			jQuery("#popup-mpdal-freight-shipping").modal("openModal");
		});
		
		var popup_freight = modal(options, jQuery('#popup-mpdal-local-delivery'));
		jQuery("#click-local-delivery").on('click',function(){ 
			jQuery("#popup-mpdal-local-delivery").modal("openModal");
		});
		
		
		////////// end
		/*jQuery(".primary .button").click(function() {
				jQuery('html, body').animate({
					scrollTop: jQuery(".field._required._error").offset().top
				}, 2000);
				jQuery('html, body').animate({
					scrollTop: jQuery(".form-login .mage-error").offset().top - 30
				}, 2000);
			});
			jQuery("#co-shipping-method-form .button.primary").click(function() {
				alert('hello');
				jQuery('html, body').animate({
					scrollTop: jQuery(".field._required._error").offset().top
				}, 2000);
			});*/
		
        }
    );
</script>

<span class="abt-our-shipp-opt" style="display:none;">about our shipping options</span>

<a href="javascript:void(0);" id="click-united-parcel-service" style="display:none;">Click Me</a>
<div id="popup-mpdal-united-parcel-service" style="display:none;">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_shipping_options')->toHtml();?> 
</div>

<a href="javascript:void(0);" id="click-freight-shipping" style="display:none;">Click Me</a>
<div id="popup-mpdal-freight-shipping" style="display:none;">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_shipping_options_freight_ship_only')->toHtml();?> 
</div>

<a href="javascript:void(0);" id="click-local-delivery" style="display:none;">Click Me</a>
<div id="popup-mpdal-local-delivery" style="display:none;">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_shipping_local_delivery')->toHtml();?> 
</div>
<style>
body.second-step .abt-our-shipp-opt {
    display: none !important;
}
.mage-error {
    margin-top: 0 !important;
}
</style>