<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
<h1 class="succes-ttl"><?php echo __('Thank You for your Order!') ?> </h1>
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
			
            <p class="ord-no"><?php echo __('Order No: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p class="ord-no"><?php echo __('Order No. <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p class="ord-desc"><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking information. Click ') ?><a href="javascript:window.print()">here</a><?php echo __(' to print a copy.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    
    
<?php     

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($block->getOrderId());


$items = $order->getAllItems();
$image = 'category_page_grid';

foreach($items as $i):
   $_product= $objectManager->create('Magento\Catalog\Model\Product')->load($i->getProductId());
   
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(280,280)->getUrl();
	 
?>
<div class="pro-data">
	<div class="pro-dataleft">
		<img src="<?php echo $productImage; ?>" />
	</div>
	<div class="pro-dataright">	
		<p class="prod-name-scs"><?php echo $_product->getName(); ?></p>
		<ul class="social-share">
			<li class="sucsmp-txt">Share:</li>
			<li class="suc-twitter"><a href="javascript:window.open('//twitter.com/home/?status=<?php echo urlencode($_product->getName() . ' (' . $_product->getProductUrl() . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Tweet') ?>">Twitter</a></li>
    
    <li class="suc-pin"><a href="javascript:window.open('//pinterest.com/pin/create/button/?url=<?php echo urlencode($_product->getProductUrl()); ?>&media=<?php echo urlencode($productImage); ?>&description=<?php echo urlencode($_product->getName()); ?>', 'pinterest', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Pin it') ?>">Pinterest</a></li>
    
    <li class="suc-fcbk"><a href="javascript:window.open('//www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($_product->getProductUrl()); ?>&t=<?php echo urlencode($_product->getName()); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Share on Facebook') ?>">Facebook</a></li>
	</ul>
	</div>
	        
    
    
</div>
<?php 

endforeach;

?>

<div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
    
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('need-help-area')->toHtml();?> 
</div>