<?php /* @var $block \Plumtree\Catalog\Block\Product\View\Extra */?>
<?php 
//$_product = $block->getProduct(); 

$relatedproductid = '';
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Plumtree\Catalog\Block\Product\View\Custom');
$currentProduct = $myBlock->getCurrentProduct();
if ($currentProduct = $myBlock->getCurrentProduct()) {
	$relatedProducts = $currentProduct->getRelatedProducts();
	if (!empty($relatedProducts)) {		
		foreach ($relatedProducts as $relatedProduct) {
			//echo $relatedProduct->getSku() . '<br />';  
			$relatedproductid = $relatedProduct->getEntityId();
			/*echo "<pre>";
			print_r($relatedProduct->debug());
			echo "</pre>";   */   
		}
	}
}




$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$curent_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');


$variable = $objectManager->create('Magento\Variable\Model\Variable');
$cus_pro_dis = $variable->loadByCode('cus_pro_dis')->getPlainValue();

$product_bysku = \Magento\Framework\App\ObjectManager::getInstance()->get('Plumtree\Catalog\Block\Probysku');
if($relatedproductid != ""){
$_relatedpro = $product_bysku->getProductById($relatedproductid);  
/*echo '<pre>';
var_dump($_relatedpro->getFinalPrice());
var_dump($_relatedpro->debug());
echo '</pre>';*/
?>

<span class="cst-top-prc simp_opt_prc "><span class="new-start<?php if($_relatedpro->getFinalPrice() && $_relatedpro->getPrice()!=$_relatedpro->getFinalPrice()){ echo " old-price";}?>"><?php echo str_replace('.00', '',$priceHelper->currency($_relatedpro->getPrice(), true, false)); ?></span>
<?php if($_relatedpro->getFinalPrice() && $_relatedpro->getPrice()!=$_relatedpro->getFinalPrice()){ ?><span class="new-start special"><?php echo str_replace('.00', '',$priceHelper->currency($_relatedpro->getFinalPrice(), true, false)); ?></span> <?php } ?></span>
<span class="cst-top-prc cust_opt_prc" style="display:none;"></span>

<div class="custom-pro-rgt-area">
<ul>
<li>
<div class="cust_rd">
<input name="EventloadRadio" type="radio" value="simpleproduct" class="simpleproduct" checked="checked" /><?php echo "<b>As Shown</b>";  ?>
</div>
<?php
echo '<p>'.nl2br($_relatedpro->getShortDescription()).'</p>';
 ?></li>
<li>
<div class="cust_rd">
<input name="EventloadRadio" type="radio" value="customproduct" class="customproduct" /> <?php echo "<b>".$curent_product->getName().'<span></span></b>' ?>
</div>
<?php 
echo '<p>'.nl2br($curent_product->getShortDescription()).'</p>';
//echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($curent_product, $curent_product->getShortDescription(), 'short_description')
 ?></li>
</ul>

</div>
<?php } ?>
<?php //$_helper = $this->helper('Magento\Catalog\Helper\Output');
//echo $_helper->productAttribute($curent_product, $curent_product->getShortDescription(), 'short_description') ?>


<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){

var cnt_related = "<?php echo $relatedproductid; ?>";
if(cnt_related){
	$('body').addClass('custom-product-view');
	//jQuery('div.cust_rd:last span').text('Starting at '+jQuery('div.options-list:first span.price-wrapper:first').text());
	jQuery("div.product-info-price").detach().prependTo('div.product-options-bottom');
	
}else{
	if (!jQuery("body").hasClass("page-product-grouped") && !jQuery("body").hasClass("page-product-configurable")) {
	$('body').addClass('simple-product-view');
	}
}

	/////////// start
	prices = []
	jQuery('#product-options-wrapper div.options-list:first .price-wrapper').each(function () {
		var price = parseFloat(jQuery(this).attr('data-price-amount'));
		if(price>0){	
		prices.push(price);
		}
	});
	//alert(prices);
	prices.sort(function(a, b) { return a - b });
	
	//////////
	pric_es = []
	jQuery('#product-options-wrapper div.options-list:first input:radio').each(function () {
		var pric_e = parseFloat(jQuery(this).attr('price'));
		if(pric_e>0){	
		pric_es.push(pric_e);
		}
	});
	pric_es.sort(function(a, b) { return a - b });
	
	
	
	if(prices[0]){
	var str_price = prices[0];
	
	var discount_percent = "<?php echo $cus_pro_dis ?>";
	
	var min_pri_ce = str_price*discount_percent/100;
	var max_pr_opt = str_price+min_pri_ce;
	
	//jQuery('.cust_opt_prc').html('<span class="new-start">starting at</span>$'+max_pr_opt+"===="+str_price.toLocaleString());
	/*jQuery('.cust_opt_prc').html('<span class="new-start-new">starting at</span><span class="cst-top-prc-new simp_opt_pr-new " ><span class="new-start old-price">$'+max_pr_opt.toLocaleString()+'</span><span class="new-start special">$'+str_price.toLocaleString()+'</span> </span>');*/
		if(max_pr_opt==str_price){
			jQuery('.cust_opt_prc').html('<span class="new-start-new">starting at</span><span class="cst-top-prc-new simp_opt_pr-new " ><span class="new-start">$'+max_pr_opt.toFixed(2).replace('.00','').replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,")+'</span> </span>');
		}else{
			jQuery('.cust_opt_prc').html('<span class="new-start-new">starting at</span><span class="cst-top-prc-new simp_opt_pr-new " ><span class="new-start old-price">$'+pric_es[0].toFixed(2).replace('.00','').replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,")+'</span><span class="new-start special">$'+str_price.toFixed(2).replace('.00','').replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,")+'</span> </span>');
		}
	
	}
	//////////	end

}); 

</script>