<?php
echo "hello";

?>

<?php 
/*
$product = $this->getProductBySku('Alma Chair');
echo "<pre>";
print_r($product->debug());
echo "</pre>";  
*/
?>


<?php /* @var $block \Plumtree\Catalog\Block\Product\View\Extra */?>
<?php 
//$_product = $block->getProduct(); 
/*
$relatedproductid = '';
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Plumtree\Catalog\Block\Product\View\Custom');
$currentProduct = $myBlock->getCurrentProduct();
if ($currentProduct = $myBlock->getCurrentProduct()) {
	$relatedProducts = $currentProduct->getRelatedProducts();
	if (!empty($relatedProducts)) {		
		foreach ($relatedProducts as $relatedProduct) {
			//echo $relatedProduct->getSku() . '<br />';  
			$relatedproductid = $relatedProduct->getEntityId();
			/*echo "<pre>";
			print_r($relatedProduct->debug());
			echo "</pre>";   * /   
		}
	}
}




$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$curent_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');

$product_bysku = \Magento\Framework\App\ObjectManager::getInstance()->get('Plumtree\Catalog\Block\Probysku');
$_relatedpro = $product_bysku->getProductById($relatedproductid);
/*
echo "<pre>";
print_r($_relatedpro->debug());
echo "</pre>"; * /
?>


<input name="EventRadio" type="radio" value="simple" checked="checked" onclick ="goToLocation(this.value);"/><?php echo'Stock '.$curent_product->getName().','. $curent_product->getPrice(); ?><br />
<input name="EventRadio" type="radio" value="custom" onclick ="goToLocation(this.value);"/><?php echo $_relatedpro->getName().','. $_relatedpro->getPrice(); ?><br />
<?php //echo $this->_storeManager->getStore()->getBaseUrl().$_relatedpro->getUrlKey().'.html';
* /
 ?>

<script>
/*function goToLocation(val){
 if(val == "simple")
     window.location = " <?php echo $block->getUrl().$curent_product->getUrlKey().'.html';?>";
 if(val == "custom")
     window.location = "<?php echo $block->getUrl().$_relatedpro->getUrlKey().'.html';?>";
}
* /
function load_product(val){
alert('hi');
	if(val == "simpleproduct"){
		jQeury('div.load_product').hide();
	}else{
		jQeury('div.load_product').show();
	}
}* /
</script>

<?php 


//$resultPage = $this->resultFactory->create(\Magento\Framework\Controller\ResultFactory::TYPE_PAGE);
/*<a href="javascript:void(0);" id="load_simple_product">load product</a><br />*/       
?>