<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>





<div class="pd-rgt-free-returns">
<?php $attribute_code ='stock_notification '; ?>
<?php if (isset($attribute_code)) {
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$curent_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
//echo $curent_product->getResource()->getAttribute('stock_notification')->getFrontend()->getLabel($curent_product);
$_attributeValue = $curent_product->getResource()->getAttribute('stock_notification')->getFrontend()->getValue($curent_product);
if ($_attributeValue != 'No')
 {
   echo $_attributeValue = html_entity_decode($curent_product->getResource()->getAttribute('stock_notification')->getFrontend()->getValue($curent_product));
  }
 
} 
// For Another Store Notification1
$_attributeValue = $curent_product->getResource()->getAttribute('stock_notification1')->getFrontend()->getValue($curent_product);

if ($_attributeValue != 'No') {
   echo "<br/>";
   $_attributeValue = $curent_product->getResource()->getAttribute('stock_notification1')->getFrontend()->getValue($curent_product);
   echo html_entity_decode($_attributeValue);
 }
  
   
?>
</div>





