<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items" style="border:none;">
        <thead>
            <tr style="padding-left:20px;">
                <th class="item-info" style="background-color:#000000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Items'); ?></p>
                </th>
                <th class="item-qty" style="background-color:#000000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Qty'); ?></p>
                </th>
                <th class="item-price" style="background-color:#000000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Price'); ?></p>
                </th>
            </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php
                if ($_item->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals" style="border-top:1px solid #000;">
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
