<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\GiftWrapping\Block\Product\Info */
?>
<?php if ($block->getGiftWrappingInfo()) : ?>
    <dl class="gift-wrapping" style="display:block;">
        <dt class="title"><?php /* @escapeNotVerified */ echo __('Gift Wrapping'); ?></dt>
        <?php /* we have remove content from here */ ?>
    </dl>
<?php endif; ?>
