<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 $cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 

// retrieve quote items collection
$itemsCollection = $cart->getQuote()->getItemsCollection();

// get array of all items what can be display directly
$itemsVisible = $cart->getQuote()->getAllVisibleItems();

// retrieve quote items array
 $items = $cart->getQuote()->getAllItems();

foreach($items as $item) {
	if(count($item->getProductType() != 'giftcard') > 0){
		if($item->getProductType() != 'giftcard'){ ?>
			<script type="text/javascript">
	    		require(['jquery', 'jquery/ui'], function($){
	    			jQuery(document).ready(nongiftproducts);
		    			
	    			function nongiftproducts () {
						if($('.opc-progress-bar-item').is(':visible')){
	    					var step = window.location.hash.substr(1);
							if(step == 'payment'){
			    				if($('.form-login').length > 0){
			    					$('.form-login').hide(); 
			    				}
			    			}
			    		}else {
						    setTimeout(nongiftproducts, 50); //wait 50 ms, then try again
						}
					}
				});

	    	</script>

		<?php }
	}

	if(count($item->getProduct()->getGiftcardType()) > 0){
	if($item->getProduct()->getGiftcardType() == 0){ // for not virtual product in cart
		 ?>
		<!-- checkout payment section on load disable email field for non-virtualgiftproduct types  -->
		<script type="text/javascript">
    		require(['jquery', 'jquery/ui'], function($){
	    		jQuery(document).ready(displayEmailonFirstStep1);
	    		
	    			
    			function displayEmailonFirstStep1 () {
					if($('.opc-progress-bar-item').is(':visible')){ 
					    $(".form-login").css('display','block');
						
					} else {
					    setTimeout(displayEmailonFirstStep1, 50);
					}
				}
			});
    	</script>
		
    	<?php } } ?>

	<script type="text/javascript">
		require(['jquery', 'jquery/ui'], function($){
    		jQuery(document).ready(displayEmailonFirstStep);
    			
			function displayEmailonFirstStep () {
				var count = 1;
				if($('.opc-progress-bar-item').is(':visible')){ 
				    $(".opc-progress-bar-item").each(function(index){
				    	$clsscount = count++;
					    $(this).attr("id",$clsscount+'section');
					    $('#1section').click(function(){
					    	$('.form-login').show();
					    });
					});
				} else {
				    setTimeout(displayEmailonFirstStep, 50); 
				}
			}
		});
	</script>
	<!-- Checkout Proceed button click for non-virtualgiftproduct types -->
	<script type="text/javascript">
		require(['jquery', 'jquery/ui'], function($){
    		jQuery(document).ready(proceedbtnclick);
    			
			function proceedbtnclick () {
				if($('.opc-progress-bar-item').is(':visible')){
					$('.checkout-proceed-btn-area').click(function(){
						$( document ).ajaxComplete(function() {
							var step = window.location.hash.substr(1);
							if(step == 'payment'){
			    				if($('.form-login').length > 0){
			    					$('.form-login').hide();
			    				}
			    			}
		    			});
					});
	    		}else {
				    setTimeout(proceedbtnclick, 50);
				}
			}
    	});
	</script>
	
<?php	}