<?php 
/**
 * @var \Impact\PixelIntegration\Block\InvokeEvents $block
 */
?>
<?php if($block->isEnabled()): ?>
<!-- Impact Tracking Code -->
<script type='text/javascript'>
var jsonDataLayerVars = JSON.parse('<?php echo $block->getDataLayer(); ?>');
if(jsonDataLayerVars) {
	data_layer1 = jsonDataLayerVars;
	data_layer2 = window.ir_data_layer;
	window.ir_data_layer = mergeDatalayers(data_layer1, data_layer2);
}
</script>
<?php if($block->checkShouldSendOrder()): ?>
<script type="text/javascript">
    ire('trackConversion', <?php echo $block->getEventTrackerId() ?>, window.ir_data_layer);
</script>
<?php endif; ?>
<?php endif; ?>