<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="multicheckout success checkout-success">
    <h1 class="succes-ttl"><?php echo __('Thank You for your Order!') ?> </h1>
    
    <?php if ($_orderIds = $block->getOrderIds()): ?>
    <p class="ord-no">
        <?php $flag = false ?>
        <span>
            <?php if (count($_orderIds) > 1): ?>
                <?php echo $block->escapeHtml(__('Order No: ')) ?>
            <?php else : ?>
                <?php echo $block->escapeHtml(__('Order No: ')) ?>
            <?php endif; ?>
        </span>
        <?php foreach ($_orderIds as $orderId => $incrementId): ?><?php if ($flag): ?><?php echo ', ' ?><?php endif; ?><?php $flag = true ?><a href="<?php /* @escapeNotVerified */ echo $block->getViewOrderUrl($orderId) ?>"><?php /* @escapeNotVerified */ echo $incrementId ?></a><?php endforeach; ?>
    </p>
	<p class="ord-desc"><?php echo $block->escapeHtml(__('Thanks for your order. We\'ll email you order details and tracking information.')) ?></p>
    <?php endif; ?>
    <?php echo $block->getChildHtml() ?>
    
    
<?php     
foreach ($_orderIds as $orderId => $incrementId): 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($incrementId);


$orderNo = $incrementId;

//////////// order comment start

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tbl_sales_order = $resource->getTableName('sales_order');
$tbl_quote = $resource->getTableName('quote');
$tbl_sales_order_grid = $resource->getTableName('sales_order_grid');

$sql_qry_quotid = "SELECT quote_id FROM ".$tbl_sales_order." WHERE increment_id='".$orderNo."' ";
$qt_id = $connection->fetchAll($sql_qry_quotid);

$sql_qry_getmsg = "SELECT bold_order_comment FROM ".$tbl_quote." WHERE entity_id ='".$qt_id[0]['quote_id']."' ";
$qt_msg = $connection->fetchAll($sql_qry_getmsg);


$sql_qry_update_msg = "UPDATE ".$tbl_sales_order." SET bold_order_comment = '".$qt_msg[0]['bold_order_comment']."' WHERE increment_id = ".$orderNo.";";
$connection->query($sql_qry_update_msg);
$sql_qry_update_msg1 = "UPDATE ".$tbl_sales_order_grid." SET bold_order_comment = '".$qt_msg[0]['bold_order_comment']."' WHERE increment_id = ".$orderNo.";";
$connection->query($sql_qry_update_msg1);
//////////// order comment end



$items = $order->getAllItems();
$image = 'category_page_grid';

foreach($items as $i):
   $_product= $objectManager->create('Magento\Catalog\Model\Product')->load($i->getProductId());
   
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(250)->getUrl();
	 
?>
<div class="pro-data">
	<div class="pro-dataleft">
		<img src="<?php echo $productImage; ?>" />
	</div>
	<div class="pro-dataright">	
		<p class="prod-name-scs"><?php echo $_product->getName(); ?></p>
		<ul class="social-share">
			<li class="sucsmp-txt">Share:</li>
			<li class="suc-twitter"><a href="javascript:window.open('http://twitter.com/home/?status=<?php echo urlencode($_product->getName() . ' (' . $_product->getProductUrl() . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Tweet') ?>">Twitter</a></li>
    
    <li class="suc-pin"><a href="javascript:window.open('https://pinterest.com/pin/create/button/?url=<?php echo urlencode($_product->getProductUrl()); ?>&media=<?php echo urlencode($productImage); ?>&description=<?php echo urlencode($_product->getName()); ?>', 'pinterest', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Pin it') ?>">Pinterest</a></li>
    
    <li class="suc-fcbk"><a href="javascript:window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($_product->getProductUrl()); ?>&t=<?php echo urlencode($_product->getName()); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes');" title="<?php echo __('Share on Facebook') ?>">Facebook</a></li>
	</ul>
	</div>
	        
    
    
</div>
<?php 

endforeach;
endforeach;
?>

    <div class="actions-toolbar">
		<div class="primary">
        <a class="action primary continue" title="<?php echo $block->escapeHtml(__('Continue Shopping')) ?>" href="<?php /* @escapeNotVerified */ echo $block->getContinueUrl() ?>"><span><?php echo $block->escapeHtml(__('Continue Shopping')) ?></span></a>
		</div>
    </div>
</div>
<div class="checkout-success">
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('need-help-area')->toHtml();?>
</div>
