<script type="text/x-magento-init">
  {
    "*": {
      "Plumtree_FullActionNameAlert/js/full-action-name-alert": {
        "full_action_name": "<?php echo $this->getFullActionName(); ?>"
      },
	  "Plumtree_FullActionNameAlert/js/jquery.fancybox.pack": {
        "full_action_name": "<?php echo $this->getFullActionName(); ?>"
      }
    }
  }
</script>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('css/jquery.fancybox.min.css')?>">