<style>
.contentv1 .ibp-banner-area .ibp-banner-img img{
	max-width:790px;
	max-height:500px;
	width:100%;
}
.contentv1 .ibp-banner-area .ibp-banner-img{
	max-width:790px;
	margin:0 auto;
}	
</style>
<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categorydata = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$catego_ries = $categoryFactory->create()->addAttributeToSelect('*')->addAttributeToFilter('entity_id',$categorydata->getId())->setStore(0);

foreach ($catego_ries as $category){

$childcategories = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getData('entity_id'));           
$childcategories = $childcategories->getChildrenCategories();
					
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$catalogcategory_entity_int = $resource->getTableName('catalog_category_entity_int');
$catalogcategory_entity_varchar = $resource->getTableName('catalog_category_entity_varchar');

$sqlquery = "SELECT value  FROM ".$catalogcategory_entity_int." WHERE `attribute_id` = 53 AND `store_id` = 0 AND row_id = ".$category->getData('entity_id')."";
$cat_stic_bloc = $connection->fetchAll($sqlquery);

$cat_img = '';
$_helper    = $this->helper('Magento\Catalog\Helper\Output');
?>


<?php if($category->getData('display_mode') == 'BUYERSPICKS') { ?>
		<div class="buyerspicks">

			<div class="category-banner-area">
			<?php
			$_imgHtml   = '';
			if ($_imgUrl = $category->getImageUrl()) {
				$_imgHtml = '<div class="category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($category->getName()) . '" title="' . $block->escapeHtml($category->getName()) . '" class="image" /></div>';
				$_imgHtml = $_helper->categoryAttribute($category, $_imgHtml, 'image');
				/* @escapeNotVerified */ echo $_imgHtml;
			}	
			?>
			
			
		<?php if ($category->getDescription()): ?>
			<div class="category-description">
				<?php /* @escapeNotVerified * / echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description')*/ echo $category->getDescription(); ?>
				<div class="category-banner-btn"><a href="#"><span class="cta-btn-text">Shop All <?php echo $block->escapeHtml($category->getName());?> </span> <span class="cta-btn-icon">&nbsp;</span></a></div>
			</div>
		<?php endif; ?>
		</div>

		<?php 
		$static_block_id = $cat_stic_bloc[0]['value']; //$category->getData('landing_page');
		echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($static_block_id)->toHtml();?>

		<?php if($category->getData('contentv1')){ ?>
        <div class="contentv1">
       	 	<?php echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('contentv1'));?>
			
        </div>
        <?php } ?>

		<?php if($category->getData('contentv2')){ ?>
        <div class="contentv2">
       		<?php echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('contentv2')); ?>
        </div>
        <?php } ?>

		<?php if($category->getData('contentv3')){ ?>
        <div class="contentv3">
        	<?php echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('contentv3')); ?>
        </div>
        <?php } ?>
        
        <ul class="all-buyers-pic">
            <?php 
			$i=2; $childcnt= count($childcategories);
			foreach($childcategories as $subcat){
			
				if ($subcat->getIsActive()) {
					$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
					$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
					$subcaturl = $subcat->getUrl();

					$_imgHtml = '';
					//echo '*******'.$cat_img[0]['value'];
					
					
					$sqlquery1 = "SELECT value  FROM ".$catalogcategory_entity_varchar." WHERE `attribute_id` = 48 AND `store_id` = 0 AND row_id = ".$_category->getData('row_id')."";
					$cat_img = $connection->fetchAll($sqlquery1);
					

					if (isset($cat_img[0]['value'])) {

						$_imgHtml = '<img src="' . $this->getBaseUrl()."media/catalog/category/".$cat_img[0]['value'] . '" class="buyers-img" />';
						$_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');

						
					   ?>
					   <li class="buy-pick-child-category-list <?php if($i%2==0){ echo "odd"; }else{ echo "even";} ?>" style="display:none;">
							<div class="lf-row">
								<div class="lf-rgt-text-img-area">
									<div class="lf-text-img"><?php echo $_imgHtml; ?></div>
									<div class="lf-conent-box">
										<div class="lf-conent-text">
											<h2><?php echo $subcat->getName(); ?></h2>
											<?php echo $_category->getDescription(); ?>
											<div class="hp-siws-banner-btn-area"><div class="hp-siws-banner-btn"><a href="<?php echo $subcaturl; ?>"><span class="cta-btn-text">Read More</span> <span class="cta-btn-icon">&nbsp;</span></a></div></div>

										</div>
									</div>
								</div>
							</div>
					   </li>               
					   <?php
					   $i++;
					   
					}
				}		
			}
			?>
        </ul>
        <div class=" " id="loadMore" style="display:none;"><span>view more</span></div>
        
		<script type="text/javascript">
			require(['jquery', 'jquery/ui'], function($){
				$( document ).ready(function() {  
					$('#loadMore').show();
					size_li = $("ul.all-buyers-pic li").size();
					x=6;
					$('ul.all-buyers-pic li:lt('+x+')').show();
					$('#loadMore').click(function () {
						x= (x+5 <= size_li) ? x+5 : size_li;
						$('ul.all-buyers-pic li:lt('+x+')').show();
						 $('#showLess').show();
						if(x == size_li){
							$('#loadMore').hide();
						}
					});
					$('#showLess').click(function () {
						x=(x-5<0) ? 6 : x-5;
						$('ul.all-buyers-pic li').not(':lt('+x+')').hide();
						$('#loadMore').show();
						 $('#showLess').show();
						if(x == 6){
							$('#showLess').hide();
						}
					});
				});
			});
		</script>
		</div>
<?php 
////////////////// end BUYERSPICKS

}elseif($category->getData('display_mode') == 'BUYERSPICKSCOLLECTION'){ ?>

<?php if($category->getData('category_content1')){ ?>
        <div class="category_content1">
       	 	<?php  echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('category_content1')); ?>
        
        </div>
        
        <?php } ?>
        <?php if($category->getData('category_content2')){ ?>
        
        <div class="contentv1">
       	 	<?php echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('category_content2')); ?>
        </div>
        <?php } ?>
        <?php echo $block->getProductListHtml() ?>
        <?php 
		

////////////////// end BUYERSPICKSCOLLECTION

}else{

////////////////// start default view

 if (!$block->isContentMode() || $block->isMixedMode()): ?>
	<?php if(count($childcategories)>0 && $category->getlevel() == 2): ?>
    <?php // parent category - landing page ?>
    
	
	<div class="category-banner-area">
	<?php
    $_imgHtml   = '';
    if ($_imgUrl = $category->getImageUrl()) {
        $_imgHtml = '<div class="category-image"><img src="' . $_imgUrl . '" alt="' . $block->escapeHtml($category->getName()) . '" title="' . $block->escapeHtml($category->getName()) . '" class="image" /></div>';
        $_imgHtml = $_helper->categoryAttribute($category, $_imgHtml, 'image');
        /* @escapeNotVerified */ echo $_imgHtml;
    }	
	?>
    
    
<?php if ($category->getDescription()): ?>
    <div class="category-description">
        <?php /* @escapeNotVerified  echo $this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description') */ echo $category->getDescription(); ?>        
		<?php if($category->getData('contentv2')){ ?>
        <div class="category-banner-btn"><?php  echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('contentv2'));  ?></div>
        <?php } ?>

    </div>
<?php endif; ?>
</div>

		<?php if($category->getData('category_content1')){ ?>
        <div class="category_content1">
       	 	<?php  echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('category_content1'));  ?>
        </div>
        <?php } ?>

		<?php if($category->getData('category_content2')){ ?>
        <div class="category_content2">
       		<?php  echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('category_content2'));  ?>
        </div>
        <?php } ?>

		<?php if($category->getData('category_content3')){ ?>
        <div class="category_content2">
        	<?php  echo $objectManager->get('Magento\Cms\Model\Template\FilterProvider')->getPageFilter()->filter($category->getData('category_content3'));   ?>
        </div>
        <?php } ?>
        
        <div class="new-arrivals-section">
     <?php if($category->getData('new_arrival')==1){ ?>   
    
    	<div class="nr-heading-area">
    		<div class="nr-sub-title">New Arrivals</div>
            <div class="nr-rgt-btn-link">
                <a href="javascrip:void(0);">
                   shop new arrivals
                 </a>
             </div>
        </div>  
        <div class="block widget block-new-products grid">
            <div class="block-title">.
                <strong role="heading" aria-level="2">New Products</strong>
            </div>
                
  <div class="block-content">
    <!-- new_products_content_widget_grid-->
    <div class="products-grid grid">
      <ol class="product-items widget-new-grid">
    <?php  
	
	$i=1;
	
			$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
			 
			$appState = $objectManager->get('\Magento\Framework\App\State');
			 
			$categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
			$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
			$categoryRepository = $objectManager->get('\Magento\Catalog\Model\CategoryRepository');
			
			 
			$categoryId = $category->getId();  //$subcategory->getEntityId();
			//$category = $categoryFactory->create()->load($categoryId);
			 
			$categoryProducts = $category->getProductCollection()
										 ->addAttributeToSelect('*');
			//$categoryProducts = $categoryProducts->addAttributeToSort('position', 'ASC');
			$categoryProducts = $categoryProducts->addAttributeToSort('created_at', 'DESC');			
			//->addAttributeToSort('name', 'ASC')
			$categoryProducts->setPageSize(3);
			
			$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');						
			foreach ($categoryProducts as $product) {
				

				$options = array();
				$color = array();

				$min_price = 111111111111;
				$max_price = 0;
				$special_min_price = 111111111111;
				$special_max_price = 0;	

				if($product->getTypeId() == 'grouped' ){
				//echo '<pre>';
					$_associated_products = $product->getTypeInstance(true)->getAssociatedProducts($product);
					foreach( $_associated_products as $_associated_product ) {
						
						//$min_price[] = $_associated_product->getPrice();
						if($min_price > $_associated_product->getPrice()){
						$min_price = $_associated_product->getPrice();
						$special_min_price = $_associated_product->getFinalPrice();
						} 
						
						if($max_price < $_associated_product->getPrice()){
						$max_price = $_associated_product->getPrice();
						$special_max_price = $_associated_product->getFinalPrice();
						}
						
					}
					
				}
				?>

				<?php 
				if($product->getTypeId() == 'configurable' ){
				$repository = $objectManager->create('Magento\Catalog\Model\ProductRepository');
				$data = $product->getTypeInstance()->getConfigurableOptions($product);


				foreach($data as $attr){
				  foreach($attr as $p){
				  
				  /*echo '<pre>';
				  var_dump($p);
					echo '</pre>';*/
					$options[$p['sku']][$p['attribute_code']] = $p['option_title']."_".$p['default_title']."=swtchid=".$p['value_index'];
				  }
				}

				foreach($options as $sku =>$d){
				  $pr = $repository->get($sku); 
				  foreach($d as $k => $v){ 
					
					if($k == 'color'){ 
					$color[] = $v; 
					}
					
					}
				  //echo ' : '.$pr->getPrice()."\n";
					if($min_price > $pr->getPrice()){
						$min_price = $pr->getPrice();
					}
				}
				 }
				?>

        <li class="product-item">
        <?php if($product->getData('product_flag')){
		//echo $product->getData('product_flag');
		$pro_flag = $product->getResource()->getAttribute('product_flag')->getFrontend()->getValue($product);
		$categories = ''; $twoflag = '';
		$cats = explode(",", $pro_flag);
		$i=1;
		foreach($cats as $cat) {
			$cat = trim($cat);
			$categories .= "<span class='flag-".$i."'><img src=".$block->getViewFileUrl('images/'.$cat.'.png').">" . "</span>\n";
			$i++;
		}
		echo $categories;

		} ?>
          <div class="product-item-info"> <a href="<?php echo $product->getProductUrl(); ?>" class="product-item-photo"> <span class="product-image-container" style="width:348px;"> <span class="product-image-wrapper" style="padding-bottom: 85.985748218527%;"> <img class="product-image-photo" src="<?php 
		  echo $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_page_image_large')->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(694, 546)->getUrl(); 
		  //echo $block->getUrl('pub/media/catalog').'product'.$product->getSmallImage(); ?>" alt="<?php echo $product->getName(); ?>" width="421" height="362"></span> </span> </a>
            <div class="product-item-details"> <strong class="product-item-name"> <a title="Alma Chair New" href="<?php echo $product->getProductUrl(); ?>" class="product-item-link"><?php echo $product->getName(); ?></a> </strong> <?php 
			  if($min_price != 111111111111){
			  		if($product->getTypeId() == 'grouped' ){
								echo "<div class='price-box price-final_price'>";
								if($special_min_price>0){
								echo "<div class='old-price'>";
								}
								echo "<span class='mini-price price'>".str_replace('.00', '',$priceHelper->currency($min_price, true, false))."</span>"; 						
								if($min_price != $max_price){
								echo "<span class='max-price price'> - ".str_replace('.00', '',$priceHelper->currency($max_price, true, false))."</span>"; 
								}
								if($special_min_price>0){
								echo "</div>";
								}
								echo "</div>";
								
								if($special_min_price>0){
								echo "<div class='price-box price-final_price'><div class='special-price'><span class='mini-price price'>".str_replace('.00', '',$priceHelper->currency($special_min_price, true, false))."</span>"; 						
								if($min_price != $max_price){
								echo "<span class='max-price price'> - ".str_replace('.00', '',$priceHelper->currency($special_max_price, true, false))."</span>"; 
								}
								echo "</div></div>";
								}
								
								unset($min_price);
								unset($max_price);
								unset($special_min_price);
								unset($special_max_price);
								
							}else{
						//echo "<span class='mini-price'>Starting at</span>".$priceHelper->currency($min_price, true, false); 
						?>
                        <div class="price-box price-final_price" data-role="priceBox" data-product-id="3">
                          <div class="price-box" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
                            <p class="minimal-price"> <span class="price-label">Starting at</span> <span class="price-container tax weee" style=""> <span data-price-amount="1" data-price-type="" class="price-wrapper "> <span class="price"><?php echo str_replace('.00', '',$priceHelper->currency($min_price, true, false)); ?></span> </span> </span> </p>
                          </div>
                        </div>

                        <?php 
					}
					
			  }else{
			  ?>
			  
              <div class="price-box price-final_price" data-role="priceBox" data-product-id="4"> <span class="price-container price-final_price tax weee" style=""> <span id="product-price-4" data-price-amount="2495" data-price-type="finalPrice" class="price-wrapper "> <span class="price"><?php echo str_replace('.00', '',$priceHelper->currency($product->getPrice(), true, false)); ?></span> </span> </span> </div>
              <?php 
			  }
			  ?>   
              <div class="product-item-actions">
                
                
              </div>
            <?php 
			if($product->getRelatedProducts()){
			echo '<div class="available_coption">custom options available</div>';
			}
			?>  
            
            
			<?php if($product->getTypeId() == 'configurable' ){ ?>
            <div class="available_color"></div>
            <div class='custom-option'>
            <div class="swatch-attribute color" attribute-code="color" attribute-id="#">
            <div class="swatch-attribute-options clearfix">
            <?php 
			$color = array_unique($color); 
			  
			foreach($color as $_color){ 
			$arr = explode('_', $_color);
			$important = $arr[1];
			
			$arrswtchid = explode('=swtchid=', $_color);
			$arrswt_chid = $arrswtchid[1];
			
			

			$swatchHelper=$objectManager->get("Magento\Swatches\Helper\Media");
			$swatchCollection = $objectManager->create('Magento\Swatches\Model\ResourceModel\Swatch\Collection');
			// brand logo is my Visual Swatch attribute 
			$optionIdvalue=$product->getColor(); 
			$swatchCollection->addFieldtoFilter('option_id',$arrswtchid[1]);
			$item=$swatchCollection->getFirstItem();
			
	?>
             
             <div class="swatch-option image" option-type="2" option-id="13" option-label="<?php echo $arr[0]; ?>" option-tooltip-thumb="<?php echo $swatchHelper->getSwatchAttributeImage('swatch_thumb', $item->getValue()); ?>" option-tooltip-value="<?php echo $swatchHelper->getSwatchAttributeImage('swatch_image', $item->getValue()); ?>" "="" style="background: url(<?php echo $swatchHelper->getSwatchAttributeImage('swatch_image', $item->getValue()); ?>) no-repeat center; background-size: initial;"></div>
             
			<?php }	 ?>
              </div>
               </div>
             </div>
             <?php
			}
			
			?>
            <a class="weltpixel_quickview_button_v2 weltpixel-quickview" data-quickview-url="<?php echo $block->getUrl();?>weltpixel_quickview/catalog_product/view/id/<?php echo $product->getId(); ?>/" href="javascript:void(0);"><span><?php echo __('Quick View') ?></span></a>
            </div>
          </div>
        </li>
		<?php 


			}

	?>
    
    </ol>
    </div>
    
  </div>
  
  	<div class="sponsor-media-count-6881703303  sponsor-media-count">
  	</div>
  	<div class="nr-pn-btn-area"><span id="prev-6881703303" class="prev">&nbsp;</span>
	<span id="next-6881703303" class="next">&nbsp;</span>
        </div>
        
        
</div>  
	
    <?php } ?>
	</div>

    
    

    
    <?php else: ?>
    <?php /*?> Default View <?php */?>
        <?php echo $block->getProductListHtml() ?>
    <?php endif; ?>
<?php endif; ?>
<?php 
}
}
?>

<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
	$( document ).ajaxComplete(function() {  
		$('div.swatch-attribute.color').each(function(){
			$(this).parent().find('div.available_color').html('Available in '+$('div.swatch-option', $(this)).length+' Colors');
			$(this).parent().parent().find('div.available_color').html('Available in '+$('div.swatch-option', $(this)).length+' Colors');
		});
	});
});

</script> 
