<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field<?php /* @escapeNotVerified */ echo $class; ?>">
    <label class="label label-title" for="select_<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span>&nbsp;<?php echo  $block->escapeHtml(ucwords(str_replace('_',' ',$_option->getTitle()))) ?>:&nbsp;</span><span class="co-pricenew"><span style="color: #989898;">please select</span></span><span class="arrow"></span>
    </label>
    <div class="control <?php echo strtolower(str_replace(' ','',$_option->getTitle()));?>" style="display:none;">
        <?php echo $block->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>    
        
    </div>
</div>

