<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
 
/*
echo $controllerName = $this->getRequest()->getControllerName();
echo '-'.$actionName = $this->getRequest()->getActionName();
echo '-'.$routeName = $this->getRequest()->getRouteName();
echo '-'.$moduleName = $this->getRequest()->getModuleName();
*/
//checkout-addresses-multishipping-multishipping
 
if($this->getRequest()->getRouteName()=='multishipping'){ ?>

<div class="checkout-index-index multi-ch-steps">
<ul class="opc-progress-bar">
        <li class="opc-progress-bar-item <?php if($this->getRequest()->getActionName()=='addresses' || $this->getRequest()->getActionName()=='newShipping'){ echo ' _active'; } ?>">
            <span><a href="<?php echo $this->getBaseUrl();?>multishipping/checkout/addresses/">Shipping Information</a></span>
        </li>
        <li class="opc-progress-bar-item <?php if($this->getRequest()->getActionName()=='shipping'){ echo ' _active'; } ?>">
            <span><a href="<?php echo $this->getBaseUrl();?>multishipping/checkout/shipping/">Shipping Method</a></span>
        </li>
        <li class="opc-progress-bar-item <?php if($this->getRequest()->getActionName()=='billing'){ echo ' _active'; } ?>">
            <span><a href="<?php echo $this->getBaseUrl();?>multishipping/checkout/billing/">Payment</a></span>
        </li>
        <li class="opc-progress-bar-item <?php if($this->getRequest()->getActionName()=='overview'){ echo ' _active'; } ?>">
            <span><a href="<?php echo $this->getBaseUrl();?>multishipping/checkout/overview/">Order Review</a></span>
        </li>
</ul>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('need-help-area')->toHtml(); ?>
</div>
 <?php
 }
 ?>
 <?php
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
<div class="page-title-wrapper<?php /* @escapeNotVerified */ echo $cssClass; ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getId();?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?php /* @escapeNotVerified */ echo $block->getAddBaseAttributeAria(); ?>"
        <?php endif; ?>>
        <?php /* @escapeNotVerified */ echo $title ?>
    <span class="itemcnt"></span>
    </h1>
    
    <?php echo $block->getChildHtml(); ?>
</div>
<?php endif; ?>
