<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Catalog\Block\Product;
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
// using object Managr 
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productModel = $objectManager->get('Magento\Catalog\Model\Product');
$image = 'category_page_grid';


$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$category = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
$collection = $productCollection->create()
         ->addAttributeToSelect('*')
        ->addCategoryFilter($category)
		->addAttributeToSort('name', 'ASC')
         ->load();
$collection = $collection->addAttributeToSort('name', 'ASC');
$collection->addAttributeToFilter(
                            'status', array('eq' => \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED)
                        );

?>	
       <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('request-a-free-swatch')->toHtml();?>   
       
  
		<div class="spinner"></div>
         <div class="products wrapper" style="display:none;">
        <?php // $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($collection as $_product): ?>
         <div class="product-item-info" data-container="product-grid">
    <?php 
	 // For loading Image 
	 $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	 $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(750)->getUrl();
	 $productImage1 = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300)->getUrl();
	 ?>
     
      <?php //  Loading Product Image ?>
     <a class="icon-zoom-in" href="<?php echo $productImage ?>"><img id="imageLoader" src="<?php echo $productImage1; ?>" width="150" height="150"/></a>
     <?php /*<a class="product-item-link" href="javascript:void(0)"> <img id="imageLoader" src="<?php echo $productImage; ?>" width="150" height="150"/></a>*/?>
     <div class="product details product-item-details">
     <?php $_productName = $block->stripTags($_product->getName(), null, true); ?>
     
        <?php //  Loading Product Name ?>                
       <div class="product name product-item-name">
           
     <?php  echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?> </a></div>
                                 
      <?php //  Loading Zoom  Name ?>  
      <a class="icon-zoom-in" href="<?php echo $productImage ?>">Zoom</a>
      
   <?php //  Loading Add to cart Button with form key  ?>
   <?php // using List helper for Add to cart 
    $listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
    $addToCartUrl =  $listBlock->getAddToCartUrl($_product); 
   if(!$_product->getCom()){ ?>
 <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
 <?php echo $block->getBlockHtml('formkey')?>
 <button type="submit"
  title="<?php echo $block->escapeHtml(__('add to bag')); ?>"
 class="action tocart primary">
  <span><?php /* @escapeNotVerified */ echo __('add to bag') ?></span>
 </form>
 <?php } ?>     
 </div>  
</div><?php endforeach; ?>
  </div>
  
   
   <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
   </script>
  <script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
   $( document ).ajaxComplete(function() {
     $('.icon-zoom-in').fancybox({
    fitToView: false,
    beforeShow: function () {
        this.width = 500;
        this.height = 500;
    }
    });
   

	/* Different effects */
	// Change title type, overlay closing speed		
	$(".fancybox-effects-a").fancybox({
				helpers: {
					title : {
						type : 'outside'
					},
					overlay : {
						speedOut : 0
					}
				}
			});		
 // Disable opening and closing animations, change title type
	$(".fancybox-effects-b").fancybox({
				openEffect  : 'none',
				closeEffect	: 'none',

				helpers : {
					title : {
						type : 'over'
					}
				}
			});		
			
/*Button helper. Disable animations, hide close button, change title type and content */
	$('.fancybox-buttons').fancybox({
				openEffect  : 'none',
				closeEffect : 'none',

				prevEffect : 'none',
				nextEffect : 'none',

				closeBtn  : false,

				helpers : {
					title : {
						type : 'inside'
					},
					buttons	: {}
				},

				afterLoad : function() {
					this.title = 'Image ' + (this.index + 1) + ' of ' + this.group.length + (this.title ? ' - ' + this.title : '');
				}
			});		
/*  Thumbnail helper. Disable animations, hide close button, arrows and slide to next gallery item if clicked */			
    $('.fancybox-thumbs').fancybox({
				prevEffect : 'none',
				nextEffect : 'none',

				closeBtn  : false,
				arrows    : false,
				nextClick : true,

				helpers : {
					thumbs : {
						width  : 50,
						height : 50
					}
				}
			});
}); 

// request swatch start
	var c_url      = window.location.href;
	var buyspic = c_url.replace(/\-/g, '');
	if(buyspic.indexOf("requestaswatch") > -1) {
		jQuery( document ).ajaxComplete(function() {
		jQuery('div.products').show();
		jQuery('div.spinner').hide();
		});
	}
	// request swatch end
	
	
});       
           
			
	</script>			

<style type="text/css">
		/*.title {
			display:none;
        }*/
     .fancybox-inner {
       width:300px;
      height:400px;
  } 
  .fancybox-item fancybox-close {
  background-image: url(images/fancybox_sprite.png);
  }
        
		
.spinner {
  width: 40px;
  height: 40px;
  background-color: #333;

  margin: 100px auto;
  -webkit-animation: sk-rotateplane 1.2s infinite ease-in-out;
  animation: sk-rotateplane 1.2s infinite ease-in-out;
}

@-webkit-keyframes sk-rotateplane {
  0% { -webkit-transform: perspective(120px) }
  50% { -webkit-transform: perspective(120px) rotateY(180deg) }
  100% { -webkit-transform: perspective(120px) rotateY(180deg)  rotateX(180deg) }
}

@keyframes sk-rotateplane {
  0% { 
    transform: perspective(120px) rotateX(0deg) rotateY(0deg);
    -webkit-transform: perspective(120px) rotateX(0deg) rotateY(0deg) 
  } 50% { 
    transform: perspective(120px) rotateX(-180.1deg) rotateY(0deg);
    -webkit-transform: perspective(120px) rotateX(-180.1deg) rotateY(0deg) 
  } 100% { 
    transform: perspective(120px) rotateX(-180deg) rotateY(-179.9deg);
    -webkit-transform: perspective(120px) rotateX(-180deg) rotateY(-179.9deg);
  }
}


/*
spiner 1
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid blue;
  border-bottom: 16px solid blue;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}*/
</style> 
   
  