<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
?>
<div class="mini-sticky-option-area"><div class="stikey_size" style="display:none;"></div>
<div class="stikey_color" style="display:none;"></div></div>
<div class="product-options-wrapper" id="product-options-wrapper"<?php /* @escapeNotVerified */ echo $required; ?>>
    <div class="fieldset" tabindex="0">
        <?php echo $block->getChildHtml('', true);?>
    </div>
</div>


<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){

jQuery("span.co-price span.price-notice span.new-start.old-price:empty").remove();
$( document ).ajaxComplete(function() {  
$('div.select-item:last').remove();
	$('div.swatch-option').click(function(){
		//alert('lklklk');
		var cnt_selected = 0;
		var cnt_attribute = $('div.swatch-attribute-options').length;
		//var selected_lbl_color = '';
		var selected_lbl_color = $(this).attr('option-label'); 
		$('div.stikey_color').html('<span>Color:<span>'+selected_lbl_color);
		setTimeout(function() {
		$('div.swatch-attribute').each(function(){
			if($(this).attr('option-selected')){
			cnt_selected++;
			}
			
		});
		
		if(cnt_selected == cnt_attribute){
			//$('button.select-item').find('span').text('add to bag');	
			//$('button.select-item').attr("disabled", false);
			//$('button.select-item').show();
			//$('button.scrolltodiv').hide();
			//$('div.product-options-bottom div.actions').removeClass('hidebtn');
			$('button.scrolltodiv').addClass('btn-hide');
			$('span.price-container.price-final_price.tax.weee').show();
			$('#product-addtocart-button').removeClass('btn-hide');			
			$('#product-addtocart-button').addClass('addbtn-show');
			
			//$('p.rprc').hide();
		}else{
			//$('button.select-item').find('span').text('Select Options');
			//$('button.select-item').attr("disabled", true);
			//$('button.select-item').hide();
			//$('button.scrolltodiv').show();
			//$('div.product-options-bottom div.actions').addClass('hidebtn');
			$('span.price-container.price-final_price.tax.weee').hide();
			$('button.scrolltodiv').removeClass('btn-hide');
			$('#product-addtocart-button').addClass('btn-hide');
			
			$('#product-addtocart-button').removeClass('addbtn-show');
			$('p.rprc').show();
		}
		
		}, 1400);
	});

	$('select.swatch-select').change(function(){
		var cnt_selected = 0;
		var cnt_attribute = $('div.swatch-attribute-options').length;
		//var selected_lbl_size = '';
		var selected_lbl_size = $("select.swatch-select option[value='"+$(this).val()+"']").text(); // $(this).text(); 
		//alert($(this).val()+' ********* '+selected_lbl_size);
		
		$('div.stikey_size').html('<span>Size:<span>'+selected_lbl_size);
		setTimeout(function() {
		$('div.swatch-attribute').each(function(){
			if($(this).attr('option-selected')){
			cnt_selected++;
			}
			
		});
		
		if(cnt_selected == cnt_attribute){
			//$('button.select-item').find('span').text('add to bag');		
			//$('button.select-item').attr("disabled", false);
			//$('div.product-options-bottom div.actions').removeClass('hidebtn');

			$('button.scrolltodiv').addClass('btn-hide');
			$('span.price-container.price-final_price.tax.weee').show();
			$('#product-addtocart-button').removeClass('btn-hide');
			$('#product-addtocart-button').addClass('addbtn-show');
			//$('p.rprc').hide();
		}else{
			//$('button.select-item').find('span').text('Select Options');
			//$('button.select-item').attr("disabled", true);
//			$('div.product-options-bottom div.actions').removeClass('hidebtn');

			$('span.price-container.price-final_price.tax.weee').hide();
			$('button.scrolltodiv').removeClass('btn-hide');
			$('#product-addtocart-button').addClass('btn-hide');
			$('#product-addtocart-button').removeClass('addbtn-show');

			
			$('p.rprc').show();
		}
		
		}, 1400);
	});
	

	
}); 
}); 

</script>