<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="contact-form-area">
<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getBaseUrl()."contact-us/index/post/";//$block->getFormAction(); ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Connect with us') ?></span></legend><br />
        <?php
		$i = $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName());
		$h = $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name'));
		//var_dump($i); var_dump($h) ; die;
		if($i == null){
			$val1 = $val2 = $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name'));
			
		}
			else {
             $UserNames = explode(" ", $i);			
			$val1 = $UserNames[0];
			$val2 = $UserNames[1];
			}
		//$k = $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ;
		//echo $k;
		//if(!isset($_SESSION[$k]))
		//$UserNames = explode(" ", $k);
		?>
		
        <div class="field firstname required">
            <input name="name" id="flname" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value=""  type="hidden"  />
            
            <div class="control">
                <input name="firstname" id="firstname" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $val1 ;?>" class="input-text" type="text" placeholder="First Name" data-validate="{required:true}" autocomplete="given-name"/>
            </div>
        </div>
        
         <div class="field lastname required">
            
            <div class="control">
                <input name="lastname" id="lastname" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $val2; ?>" class="input-text" type="text" placeholder="Last Name" data-validate="{required:true}" autocomplete="family-name"/>
            </div>
        </div>
        
       
        
        <div class="field email required">           
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email Address') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" placeholder="Email Address" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        
        <div class="field comment required">
           
            <div class="control">
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}" placeholder="Message..." ><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('SEND') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('SEND') ?></span>
            </button>
        </div>
    </div>
</form></div>
<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
	var fl_name = '';
	$("#firstname").focusout(function(){
		fl_name = $('#firstname').val() + ' ' +$('#lastname').val();
		$('#flname').val(fl_name);
	});
	$("#lastname").focusout(function(){
		fl_name = $('#firstname').val() + ' ' +$('#lastname').val();
		$('#flname').val(fl_name);
	});
});
</script>