<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\GiftMessage\Block\Cart\Item\Renderer\Actions\GiftOptions */


$_item = $block->getItem();
$product = $_item->getProduct();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productObject = $objectManager->get('Magento\Catalog\Model\Product');
$prod_uct = $productObject->loadByAttribute('sku', $product->getData('sku'));
if($prod_uct->getData('gift_message_available')==1){
?>
<?php if (!$block->isVirtual()): ?>
    <div id="gift-options-cart-item-<?php /* @escapeNotVerified */ echo $block->getItem()->getId() ?>"
        data-bind="scope:'giftOptionsCartItem-<?php /* @escapeNotVerified */ echo $block->getItem()->getId() ?>'"
        class="gift-options-cart-item">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#gift-options-cart-item-<?php /* @escapeNotVerified */ echo $block->getItem()->getId() ?>": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
        </script>
    </div>
<?php endif ?>
<?php } ?>