<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method" style="text-align:left; margin:0;">
    <dt class="title" style="color:#000000;text-align:left; margin:0;"><?php /* @noEscape */ echo $title; ?></dt>
<?php if ($specificInfo):?>
    <dd class="content" style="text-align:left; margin:0;">
        <table class="data table"  style="text-align:left; margin:0;">
            <caption style="text-align:left;color:#000000;margin:0;" class="table-caption-1"><?php /* @noEscape */ echo $title; ?></caption>
            <?php foreach ($specificInfo as $label => $value):?>
                <tr>
                    <th style="font-family: Arial,Helvetica,sans-serif;font-size: 15px;font-weight:normal; color: #000000; padding:10px 20px;margin:0;" scope="row" ><?php echo $block->escapeHtml($label)?></th>
                    <td style="font-family: Arial,Helvetica,sans-serif;font-size: 15px;font-weight:normal; color: #000000; padding:10px 20px;margin:0;">
                        <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))));?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </dd>
<?php endif;?>
</dl>
<?php echo $block->getChildHtml()?>