<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php 
/*
$productId = $block->getSaleableItem()->getId();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $_objectManager->get('\Magento\Catalog\Model\Product')->load($productId);
$productTypeInstance = $_objectManager->get('Magento\ConfigurableProduct\Model\Product\Type\Configurable');
$productAttributeOptions = $productTypeInstance->getConfigurableAttributesAsArray($_product);
echo '<pre>';
var_dump($productAttributeOptions); 
echo '</pre>';*/
?>

<?php 
$priceModel = $block->getPriceType('regular_price');
$productId = $block->getSaleableItem()->getId();
$cprice = array();
$fprice = array();
$specialprice = array();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$finalPriceAmt = $_product->getPriceInfo()->getPrice('final_price')->getValue();
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;


if ($request->getFullActionName() == 'catalog_category_view' || $request->getFullActionName() == 'catalogsearch_result_index' || $request->getFullActionName() == 'catalog_product_view' || $request->getFullActionName() == 'quickview_product_view' || $request->getFullActionName() == 'weltpixel_quickview_catalog_product_view') {?>
<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */

if($_product->getIsSalable()){
$_children = $_product->getTypeInstance()->getUsedProducts($_product);
	foreach ($_children as $child){
		$child->getID();
		$cprice[] = $child->getPrice();
		$fprice[] = $child->getPriceInfo()->getPrice('final_price')->getValue();
		if($child->getFinalPrice()){
		$specialprice[] = $child->getFinalPrice();
		}
		//echo $block->renderAmountMinimal();
	}
	sort($cprice);
	sort($fprice);
	sort($specialprice);
	$first = reset($cprice);
	$last = end($cprice);
	
	$special_first = reset($specialprice);
	$special_last = end($specialprice);
	
	//$low = number_format($first,0);
	//$high = number_format($last,0);
	$low = $first; //number_format($first,0);
	$high = $last; //number_format($last,0);
	/*echo '<pre>';
	print_r($specialprice);
	echo '</pre>';*/
	$special_low = $special_first;
	$special_high = $special_last;
	
	
	$ffirst = reset($fprice);
	$flast = end($fprice);
	$flow = '$'.number_format($ffirst,0);
	$fhigh = '$'.number_format($flast,0);?>
    <p class="rprc <?php if($special_high){ echo " old-price";} ?>"><span class="retail-f"><?php echo str_replace('.00', '',$priceHelper->currency($low, true, false)); ?></span> - <span class="retail-f"><?php echo str_replace('.00', '',$priceHelper->currency($high, true, false));?></span></p>
    
    <?php  if($special_high){ ?>
    <p class="rprc special"><span class="retail-f"><?php echo str_replace('.00', '',$priceHelper->currency($special_low, true, false)); ?></span> - <span class="retail-f"><?php echo str_replace('.00', '',$priceHelper->currency($special_high, true, false));?></span></p>
    <?php } ?>
    
    <?php if ($_product->getTypeId() == 'configurable') {
        $priceModel = $block->getPriceType('regular_price');
        
        /** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
        $finalPriceModel = $block->getPriceType('final_price');
        $idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
        $schema = ($block->getZone() == 'item_view') ? true : false;
        ?>
        <?php if ($block->hasSpecialPrice()): ?>
            <span class="special-price">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                    'display_label'     => __('Special Price'),
                    'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                    'price_type'        => 'finalPrice',
                    'include_container' => true,
                    'schema' => $schema
                ]); ?>
            </span>
            <span class="old-price sly-old-price no-display">
                <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
                    'display_label'     => __('Regular Price'),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                ]); ?>
            </span>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
                'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
                'price_type'        => 'finalPrice',
                'include_container' => true,
                'schema' => $schema
            ]); ?>
        <?php endif; ?>
        
        <?php if ($block->showMinimalPrice()): ?>
            <?php if ($block->getUseLinkForAsLowAs()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
                    <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
                </a>
            <?php else:?>
                <span class="minimal-price-link">
                    <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
                </span>
            <?php endif?>
        <?php endif;
		
		} ?>

<?php }
}else{
?>

<?php
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->hasSpecialPrice()): ?>
    <span class="special-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </span>
    <span class="old-price sly-old-price no-display">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php else: ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); ?>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?php /* @escapeNotVerified */ echo $block->getSaleableItem()->getProductUrl(); ?>" class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?php /* @escapeNotVerified */ echo $block->renderAmountMinimal(); ?>
        </span>
    <?php endif?>
<?php endif; ?>

<?php

}
?>