<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Checkout\Block\Cart */
?>
<?php /* start 			

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('core_config_data');

$sql_freeshipping_enable = "SELECT value FROM " . $tableName." WHERE `path` = 'carriers/freeshipping/active'";
$result_freeshipping_enable = $connection->fetchAll($sql_freeshipping_enable);


$sql_freeshipping_amt = "SELECT value FROM " . $tableName." WHERE `path` = 'carriers/freeshipping/free_shipping_subtotal'";
$result_freeshipping_amt = $connection->fetchAll($sql_freeshipping_amt);


//$variables = $objectManager->create('Magento\Variable\Model\Variable');
//$custom_var_value = $variables->loadByCode('free_shipping_minimum_value')->getPlainValue();

$custom_var_value = $result_freeshipping_amt['0']['value'];

$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 
$subTotal = $cart->getQuote()->getSubtotal();
$grandTotal = $cart->getQuote()->getGrandTotal();

$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');

$new_final = $custom_var_value - $grandTotal;

$style = '';
$_msg = '';
if($result_freeshipping_enable['0']['value'] != 0){
	if($new_final<=0){
		//$style = 'style="display:none;"';
		$_msg = "YOU Will RECEIVE FREE SHIPPING ON YOUR ORDER !";
	}else{
		$_msg = "ADD ".str_replace('.00', '',$priceHelper->currency($new_final, true, false))." To RECEIVE FREE SHIPPING ON YOUR ORDER !";				
	}
}*/
?>

<?php if (!$block->hasError()): ?>
<?php $methods = $block->getMethods('methods') ?: $block->getMethods('top_methods') ?>
<ul class="checkout methods items checkout-methods-items">
<?php /*<div class="add-free-shipping-section <?php if($new_final<=0){ echo ' green-msg'; } ?>" <?php echo $style; ?>><span class="add-free-shipping"><?php echo $_msg; ?></span></div> */ ?>
<?php foreach ($methods as $method): ?>
    <?php if ($methodHtml = $block->getMethodHtml($method)): ?>
    <li class="item"><?php /* @escapeNotVerified */ echo $methodHtml; ?></li>
    
    <?php endif; ?>
<?php endforeach; ?>
</ul>
<?php endif; ?>
<div class="checkout-mcafree-secure-btn-area"><a href="https://www.mcafeesecure.com/verify?host=jaysonhome.com" target="_blank" class="checkout-mcafreesecure-logo">&nbsp;</a></div>