<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<?php
/*
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$_qty = 9999;	
/*
$cart = $objectManager->get('\Magento\Checkout\Model\Cart');
$helper = $this->helper('\Magento\Checkout\Helper\Cart');
echo '<br>*'.$helper->getSummaryCount();

echo '<br>**'.$totalQuantity = $cart->getQuote()->getItemsQty();
if($totalQuantity){
	
$result = explode('.',$totalQuantity);
$_qty = $result[0];
}else{
$_qty = 0;	
}* /
$customerSession = $objectManager->create('Magento\Checkout\Model\Session');
$quote_id_1 = $customerSession->getData('quote_id_1');


$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tbl_quote = $resource->getTableName('quote');

$sql_qry_getmsg = "SELECT items_qty FROM ".$tbl_quote." WHERE entity_id ='".$quote_id_1."' ";
$get_qty = $connection->fetchAll($sql_qry_getmsg);

//echo '<br>___'.$get_qty['0']['items_qty'];
if($get_qty){
$result = explode('.',$get_qty['0']['items_qty']);
$_qty = $result[0];
}
*/
?>

<script>

require(['jquery'], function($){
	/////
			$.ajax({
                    url:"<?php echo $this->getUrl("qtycount"); ?>",
                    type:'POST',
                    showLoader: true,
                    dataType:'json',      
                    success:function(response){
                        //put your code
						console.log(response);
						jQuery('span.mycntnumber1').text(response);
                    }
                });
				
			/////
});
</script>
<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php /* @escapeNotVerified */ echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php /* @escapeNotVerified */ echo __('My Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
			<span class="counter-number mycntnumber1" ><?php //$helper->getSummaryCount(); ?></span>
            <span class="counter-number mycntnumber2" style="display:none;"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: getCartParam('summary_count') -->
                <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                <!-- ko i18n: 'items' --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
   

    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
            <?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('free-shipping')->toHtml();?>
                <!-- ko template: getTemplate() --><!-- /ko -->
                
            </div>
             
            <?php echo $block->getChildHtml('minicart.addons'); ?>
           
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>

</div>

