<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

$paramtr = '';
if($this->getRequest()->getParam('q')){
$paramtr = $this->getUrl().'catalogsearch/result/?q='.$this->getRequest()->getParam('q').'&';
}else{
$paramtr = '?';
}
?>
<div class="toolbar-sorter sorter">
	
    <dl id="sorter" class="sorter-dropdown">
    <?php if($this->getRequest()->getModuleName()=='catalogsearch'){ ?>
			<dt><a href="javascript:void(0)"><span><?php /* @escapeNotVerified */ echo __('') ?></span></a></dt>
	<?php }else{ ?>
    		<dt><a href="javascript:void(0)"><span><?php /* @escapeNotVerified */ echo __('Curated') ?></span></a></dt>
     <?php 	} ?>
			
					<dd>
						<ul>
						 <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
							<?php  if ($_order != 'Position') :  ?>
                                 <li <?php if ($block->isOrderCurrent($_key)): ?>
			                    selected="selected" class="selected"
                					<?php endif; ?> >	
                                 <a href="<?php echo $paramtr; ?>product_list_order=<?php echo $_key; ?>">
									<?php echo $block->escapeHtml(__($_order)) ?></a>
                                   </li>
                            
                               <?php endif; ?>
                            <?php endforeach; ?>													   
						</ul>
					</dd>
				</dl>
    
	    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
    
</div>
