<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order    = $block->getOrder() ?>
<?php if ($_shipment && $_order): ?>
    <table class="email-items" style="border: 0;">
        <thead>
            <tr style="padding-left:20px;">
                <th class="item-info" style="background-color:#000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Items'); ?></p>
                </th>
                <th class="item-qty" style="background-color:#000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;text-align:right;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Qty'); ?></p>
                </th>
            </tr>
        </thead>
        <?php foreach ($_shipment->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
