<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_creditmemo = $block->getCreditmemo() ?>
<?php $_order      = $block->getOrder() ?>
<?php if ($_creditmemo && $_order): ?>
    <table class="email-items" style="border:none;">
        <thead>
            <tr style="padding-left:20px;">
                <th class="item-info" style="background-color:#000000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Items'); ?></p>
                </th>
                <th class="item-qty" style="background-color:#000000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Qty'); ?></p>
                </th>
                <th class="item-subtotal" style="background-color:#000000;font-family: Arial,Helvetica,sans-serif;font-size: 14px;color: #ffffff;text-transform:uppercase; letter-spacing:0.1em;font-weight:normal;padding:10px 20px;text-align:right;">
                    <p style="margin-bottom:0px;"><?= /* @escapeNotVerified */  __('Subtotal'); ?></p>
                </th>
            </tr>
        </thead>
        <?php foreach ($_creditmemo->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('creditmemo_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
