<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
<?php  $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');?>


<?php  $product =  $_product->getFormatedprice(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; 
foreach($_associatedProducts as $_associatedProduct) {
    if($showPrice = $_associatedProduct->getPrice()) {
   echo  $formattedPrice = str_replace('.00', '',$priceHelper->currency($showPrice));
       }
   }  
    
       


  ?>

   
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
    
<div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
        </div>
        
    <?php endif; ?>
<?php endif; ?>
