<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>

<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>

<?php  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
 ?>
<?php 
$min_price = 111111111111;
$max_price = 0;
$special_price_yes = 0;
$special_min_price = 111111111111;
$special_max_price = 0;	

$allchild_saleable = 0;

foreach( $_associatedProducts as $_associated_product ) {

	if($min_price > $_associated_product->getPrice()){
	$min_price = $_associated_product->getPrice();
	$special_min_price = $_associated_product->getFinalPrice();
	} 
	
	if($max_price < $_associated_product->getPrice()){
	$max_price = $_associated_product->getPrice();
	$special_max_price = $_associated_product->getFinalPrice();
	}

	if ($_associated_product->isSaleable()){
		$allchild_saleable = 1;
	}

}


				echo "<div class='price-box price-final_price'>";
				if($special_min_price>0 && $min_price != $special_min_price){
				echo "<div class='old-price'>";
				}
				echo "<span class='mini-price price'>".str_replace('.00', '',$priceHelper->currency($min_price, true, false))."</span>"; 						
				if($min_price != $max_price && $special_min_price != $special_max_price){
				echo "<span class='max-price price'> - ".str_replace('.00', '',$priceHelper->currency($max_price, true, false))."</span>"; 
				}
				if($special_min_price>0 && $min_price != $special_min_price){
				echo "</div>";
				}
				echo "</div>";
				
				if($special_min_price>0 && $min_price != $special_min_price){
					$special_price_yes = 1;
				echo "<div class='price-box price-final_price'><div class='special-price'><span class='mini-price price'>".str_replace('.00', '',$priceHelper->currency($special_min_price, true, false))."</span>"; 						
				if($min_price != $max_price && $min_price != $special_min_price){
				echo "<span class='max-price price'> - ".str_replace('.00', '',$priceHelper->currency($special_max_price, true, false))."</span>"; 
				}
				echo "</div></div>";
				}
				
				unset($min_price);
				unset($max_price);
				unset($special_min_price);
				unset($special_max_price);
				
?>
<?php if($special_price_yes==1){ ?>
<div class="price-box price-final_price special_yes">
<?php }else{ ?>
<div class="price-box price-final_price">
<?php } ?>

<p class="rprc" style="display:none;"><span class="itemcnttotal retail-f"></span><span class="itemcnttotal_sp retail-f" style="display:none;"></span> </p></div>
<?php if($_product->isSaleable() && $allchild_saleable == 1){ ?>
<div class="table-wrapper grouped" <?php if($allchild_saleable == 1){ echo 'style="display:block"'; }else{ echo 'style="display:none"';} ?>>
    <table class="table data grouped" id="super-product-table">
        <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Grouped product items') ?></caption>
        <thead>
        <tr>
        	<th class="col picture" scope="col"><?php /* @escapeNotVerified */ echo __('Product Picture') ?></th>
            <th class="col item" scope="col"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
        <?php $count = 0  ;?>
        <?php foreach ($_associatedProducts as $_item): ?>
        <?php  $item = $_item->getId() ;?>
       <?php $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item); ?>
        <tbody>
            <tr>
            	<td class="col picture" scope="col">
                        <?php $productImage = $block->getImage($product, 'product_thumbnail_image');

						$images = $product->getMediaGalleryImages();
						if(count($images)<1){
							echo $productImage->toHtml();
						}else{
						$i=0;
						foreach($images as $child){ ?>
							
                            <a title="<?php echo $_item->getName(); ?>" class="group-img-zoom" <?php if($i!=0){ echo "style='display:none;'" ;} ?> rel="group<?php echo $item; ?>" href="<?php echo $child->getUrl(); ?>"><img alt="<?php echo $_item->getName(); ?>" src="<?php  echo $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_page_image_large')->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(150, 150)->getUrl(); //echo $child->getUrl(); ?>" style="max-width: fit-content; max-width:-webkit-fit-content; max-width: -moz-fit-content; width: 75px;" ></a>

						<?php $i++; 
						} 
						}?>
          
                    </td>            	
                    <td data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>" class="col item">
                    <strong class="product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                        <?php if ($block->getCanShowProductPrice($_item)): ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                     <?php endif; ?>
                </td>
                <?php if ($_product->isSaleable()): ?>
                <td data-th="<?php echo $block->escapeHtml(__('Qty')); ?>" class="col qty">
                <?php if ($_item->isSaleable()) : ?>
                    <div class="control qty">
                    <input type="hidden" class="item-cnt" />
                        <input type="number" name="super_group[<?php /* @escapeNotVerified */ echo $_item->getId() ?>]"
                               data-selector="super_group[<?php /* @escapeNotVerified */ echo $_item->getId() ?>]"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */ echo $_item->getQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>"
                               class="input-text qty"
                               data-validate="{'validate-grouped-qty':'#super-product-table'}"
                               data-errors-message-box="#validation-message-box"/>
                                <span class="gp-item-price" style="display:none;"><?php echo $_item->getPrice(); ?></span>
                                <span class="gp-item-price_final" style="display:none;"><?php echo $_item->getFinalPrice(); ?></span>
                                <span class="gp-item-cnt" style="display:none;"></span>
                    </div>
                <?php else: ?>
                    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
            <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?php echo $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
        <?php  $count ++ ;		?>
        <?php endforeach; ?>
               
        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                    <?php /* @escapeNotVerified */ echo __('No options of this product are available.') ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<?php } ?>
<div id="validation-message-box"></div>


<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
 
jQuery('div.product-add-form div.price-box.price-final_price:first').addClass('rng-price');
		setTimeout(function() {

		$('.group-img-zoom').fancybox({
			prevEffect	: 'none',
			nextEffect	: 'none',
			openEffect	: 'none',
			closeEffect	: 'none',
			helpers	: {
				title	: {
					type: 'outside'
				},
				thumbs	: {
					width	: 50,
					height	: 50
				}
			}
		});
		
		}, 1400);

	
	// sticky price & item count
	var totalofitem = 0;
	var totalofitem_sp = 0;
	
	
	jQuery(".qty .control").prepend('<div class="dec button">-</div>');
  	jQuery(".qty .control").append('<div class="inc button">+</div>');
	
	jQuery(document).on("click", 'div.inc', function () {
		
		var $button = $(this);
		var oldValue = $button.parent().find("input.qty").val();
		
		if ($button.text() == "+") {
		  var newVal = parseFloat(oldValue) + 1;
		  $button.parent().find("input.item-cnt").val(newVal);
		} else {
		   // Don't allow decrementing below zero
		  if (oldValue > 0) {
			var newVal = parseFloat(oldValue) - 1;
			$button.parent().find("input.item-cnt").val(newVal);
			} else {
			newVal = 0;
			$button.parent().find("input.item-cnt").val('-1');
		  }
		  }
		
		$button.parent().find("input.qty").val(newVal);

		totalofitem = parseFloat(totalofitem) + parseFloat($(this).parent().find("span.gp-item-price").text());
		totalofitem_sp = parseFloat(totalofitem_sp) + parseFloat($(this).parent().find("span.gp-item-price_final").text());
		//totalofitemcnt++;	
			var totalofitemcnt = 0;
			
			$('.qty').each(function(){
			//if( parseFloat($(this).val()) !== 'NaN'){ 
			if( $.isNumeric($(this).val())){
			 	totalofitemcnt = totalofitemcnt + parseFloat($(this).val());
				}
			});	
			
			if(totalofitemcnt != 0){
				$('button.select-item').find('span').text('add to bag');
				$('div.select-item button.scrolltodiv').addClass(' hide');
				//alert('hide');
				$('button.select-item').show();
							
			}else{
				$('button.select-item').find('span').text('select items');
				$('div.select-item button.scrolltodiv').removeClass(' hide');
				//alert('show');
				$('button.select-item').hide();
			}
			
			if(totalofitemcnt<=0){
				$('span.itemcnt').html("");	
				jQuery('#product-addtocart-button').hide();
				jQuery('.scrolltodiv').show();
			}else{
				$('span.itemcnt').html("("+totalofitemcnt+")");	
				jQuery('#product-addtocart-button').show();
				jQuery('.scrolltodiv').hide();
			}
			
			if(totalofitem<=0){
			totalofitem = 0;
			totalofitem_sp =0;
			}
			
			$('span.itemcnttotal').html("$"+totalofitem+"");
			$('span.itemcnttotal_sp').html("$"+totalofitem_sp+"");
			
			
		$('p.rprc').show();
		$('div.rng-price').hide();
		$('div.old-price').hide();
		$('div.special-price').hide();
		
	});
	
	

	jQuery(document).on("click", 'div.dec', function () {
	
	var item_cnt = $(this).parent().find("input.item-cnt").val();
	console.log('item_cnt::'+item_cnt);
	if(item_cnt < 0){
		return false;
	}

		var $button = $(this);
		var oldValue = $button.parent().find("input.qty").val();
		
		if ($button.text() == "+") {
		  var newVal = parseFloat(oldValue) + 1;
		  $button.parent().find("input.item-cnt").val(newVal);
		} else {
		   // Don't allow decrementing below zero
		  if (oldValue > 0) {
			var newVal = parseFloat(oldValue) - 1;
			$button.parent().find("input.item-cnt").val(newVal);
			} else {
			newVal = 0;
			$button.parent().find("input.item-cnt").val('-1');
		  }
		  }
		
		$button.parent().find("input.qty").val(newVal);

		totalofitem = parseFloat(totalofitem) - parseFloat($(this).parent().find("span.gp-item-price").text());
		totalofitem_sp = parseFloat(totalofitem_sp) - parseFloat($(this).parent().find("span.gp-item-price_final").text());
	
			var totalofitemcnt = 0;
			
			$('.qty').each(function(){
			if( $.isNumeric($(this).val())){
			 	totalofitemcnt = totalofitemcnt + parseFloat($(this).val());
				}
			});	
			
			if(totalofitemcnt != 0){
				$('button.select-item').find('span').text('add to bag');
				$('div.select-item button.scrolltodiv').addClass(' hide');
				$('button.select-item').show();
						
			}else{
				$('button.select-item').find('span').text('select items');
				$('div.select-item button.scrolltodiv').removeClass(' hide');
				$('button.select-item').hide();
			}	 
			
			if(totalofitemcnt<=0){
				$('span.itemcnt').html("");	
				jQuery('#product-addtocart-button').hide();
				jQuery('.scrolltodiv').show();
				jQuery('div.product-add-form div.price-box.price-final_price:first').addClass('rng-price');
			}else{
				$('span.itemcnt').html("("+totalofitemcnt+")");	
				jQuery('#product-addtocart-button').show();
				jQuery('.scrolltodiv').hide();
				jQuery('div.product-add-form div.price-box.price-final_price:first').removeClass('rng-price');
			}
			
			if(totalofitem<=0){
			totalofitem = 0;
			totalofitem_sp = 0;
			}
			$('span.itemcnttotal').html("$"+totalofitem+"");
			$('span.itemcnttotal_sp').html("$"+totalofitem_sp+"");
			
		$('p.rprc').show();
		$('div.rng-price').hide();
		$('div.old-price').hide();
		$('div.special-price').hide();	
			

	});
	
	$("button.scrolltodiv").on('click', function (e) {
	e.preventDefault(); 
		$('html,body').animate({
			scrollTop: $("#maincontent").offset().top},800);
	});
	
	
}); 

</script>
