<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $block->getProduct(); ?>

<div class="product-add-form" style="display:none;">
    <form action="<?php /* @escapeNotVerified */ echo $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $_product->getId() ?>" />
        <input type="hidden" name="selected_configurable_option" value="" />
        <input type="hidden" name="related_product" id="related-products-field" value="" />
        <?php echo $block->getBlockHtml('formkey')?>
        <?php echo $block->getChildHtml('form_top'); ?>
        <?php if (!$block->hasOptions()):?>
            <?php echo $block->getChildHtml('product_info_form_content'); ?>
        <?php else:?>
            <?php if ($_product->isSaleable() && $block->getOptionsContainer() == 'container1'):?>
                <?php echo $block->getChildChildHtml('options_container') ?>
            <?php endif;?>
        <?php endif; ?>

        <?php if ($_product->isSaleable() && $block->hasOptions() && $block->getOptionsContainer() == 'container2'):?>
            <?php echo $block->getChildChildHtml('options_container') ?>
        <?php endif;?>
        <?php echo $block->getChildHtml('form_bottom'); ?>
    </form>
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?php echo $block->escapeHtml($_product->getId())?>]',
            priceBoxes = jQuery(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !jQuery(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $block->getJsonConfig() ?>});
    });
</script>
 
<?php if( $_product->getTypeId() == 'simple' && count($_product->getOptions()) != 0 ): ?>
<div class="select-item" style="display:none;">
<button type="submit" class="select-item action primary tocart" >
                <span><?php echo 'Select Items'; ?></span>
            </button>
</div>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$productObject = $objectManager->get('Magento\Catalog\Model\Product');
	$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 

	$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
	
	$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
	
	$_sku = '';
	$product = '';
	$productdata = '';
	$order_swatch = '';
	$pro_popup = '';
	$swatch_add = '';
	$addToCartUrl = '';
	
foreach ($_product->getOptions() as $o) {
    foreach ($o->getValues() as $value) {
        //print_r($value->getData(''));
		$_sku = $value->getData('sku');
		if($_sku){
			$product = $productObject->loadByAttribute('sku', $_sku);
			if($product){
			$addToCartUrl =  $listBlock->getAddToCartUrl($product);
			echo $_myform = '<form data-role="tocart-form1" style="display:none;" class="product-from product-from-'.$product->getId().'" action="'.$addToCartUrl.'" method="post"> <input name="form_key" type="hidden" value="'.$FormKey->getFormKey().'">  <div class="btn">    <button type="submit" title="Add to Cart"  class="action tocart primary product-from-'.$product->getId().'">    <span>order swatch</span>     </button>    </div>   </form>';
			}
		}
				
    }
}

?>
<?php endif; ?> 


<script type="text/javascript">
window.addEventListener( "pageshow", function ( event ) {
  var historyTraversal = event.persisted || ( typeof window.performance != "undefined" && window.performance.navigation.type === 2 );
  if ( historyTraversal ) {
	var radioValue = jQuery("input[name='EventloadRadio']:checked").val();
	jQuery("input[value='"+radioValue+"']").prop("checked", true).trigger("click");
  }
});

require(['jquery', 'mage/gallery/gallery'], function($){

		jQuery('input:radio.product-custom-option').click(function(){
			 var imageContainer = jQuery(this).parent().find('img.pro-ing').attr("src"); //.prev('.pro-ing');
			 jQuery('img.pro-ing').removeClass('img-broder');
			 jQuery(this).parent().find('img.pro-ing').addClass('img-broder');
			 var price_wrapper  =  jQuery(this).next().find('span.price-wrapper').text();
			 var pro_name  =  jQuery(this).next().find('span.sw-tit').text(); 
			 var pr_pls = '';
			 if(price_wrapper){
			 pr_pls = ", <span class='pluscust'>+</span>" + price_wrapper;
			 }
			 var addhtml = "<span class='opt-cnt'>"+pro_name+pr_pls+"</span><span class='opt-img'><img src="+imageContainer+" class='title-img' style='width: 35px;'></span>";
			 jQuery(this).parent().parent().parent().parent().find('span.co-pricenew').html(addhtml);
			
			
			if(jQuery('.title-img').length == jQuery('.label.label-title').length){
				jQuery('#product-addtocart-button').addClass(' opt-selected');
				jQuery('#product-addtocart-button').show();
				jQuery('button.scrolltodiv ').hide();
			}else{
				jQuery('#product-addtocart-button').removeClass(' opt-selected');
				jQuery('#product-addtocart-button').hide();
				jQuery('button.scrolltodiv ').show();
			}
			
			jQuery('span.cst-top-prc.cust_opt_prc').addClass('aftrclksw');
    	}); 

	
var scroll_height = 780;
var windowWidth = jQuery(window).width();
var addhight = 0;
var addareahight = jQuery('div.pdp-main-area').height();	
var cnt = jQuery('div.pdp-main-area').height();	
var radioval = '';
var scrol_cnt = 0;


	jQuery(document).ajaxComplete(function(){
	if(windowWidth >= 768){	
	
	jQuery(window).scroll(function() {
	
	
	if(jQuery(window).scrollTop()<200){
		
		if(radioval != jQuery('input[name=EventloadRadio]:checked').val()){
		cnt = jQuery('div.pdp-main-area').height();
		if(jQuery('div.field.required.open').length){
		addareahight = jQuery('div.field.required.open').height();	
		addareahight = addareahight + 140;
		}else{
		addareahight = jQuery('div.pdp-main-area').height()-500;	
		}
		
		addareahight = addareahight;
		}
	cnt++;
	radioval = jQuery('input[name=EventloadRadio]:checked').val();
	
	
	}

								   
	if (jQuery("body").hasClass("page-product-grouped")) {
		scroll_height = '';
		if(scrol_cnt==0){
		addareahight = addareahight+230; // 180
		}
		scrol_cnt++;
	}else if(jQuery("body").hasClass("custom-product-view")){
		if(jQuery('div.pdp-main-area').height()>100){
			addareahight = jQuery('div.pdp-main-area').height();
		}		
	}
		
		var height = jQuery(window).scrollTop();	
		
		
		if(jQuery("body").hasClass("custom-product-view")){
			if(height > addareahight) {			
				
				jQuery('.pdp-main-area-bg').addClass('fixed-pdp-sticky');
				jQuery('.column.main').addClass('pdp-sticky-except-area');
				
				jQuery('div.select-item').show();
				jQuery('div.stikey_size').show();
				jQuery('div.stikey_color').show();
				
				jQuery('span.itemcnt').show();
				jQuery('span.itemcnttotal').show();

				if (addareahight > 0) {
					jQuery('.custom-des-area.expandDiv').css('margin-top',addareahight-500+'px');
				}else{
					jQuery('.custom-des-area.expandDiv').css('margin-top',scroll_height-addareahight-500+'px');
				}			
				
				
			}else{
				jQuery('.pdp-main-area-bg').removeClass('fixed-pdp-sticky');
				jQuery('.column.main').removeClass('pdp-sticky-except-area');
				jQuery('div.select-item').hide();
				jQuery('div.stikey_size').hide();
				jQuery('div.stikey_color').hide();
				
				jQuery('span.itemcnt').hide();
				jQuery('span.itemcnttotal').show();
				jQuery('.custom-des-area.expandDiv').removeAttr("style");
				
			}
		}else{
			if(height > cnt) {			
				
				jQuery('.pdp-main-area-bg').addClass('fixed-pdp-sticky');
				jQuery('.column.main').addClass('pdp-sticky-except-area');
				
				jQuery('div.select-item').show();
				jQuery('div.stikey_size').show();
				jQuery('div.stikey_color').show();			
				jQuery('span.itemcnt').show();
				jQuery('span.itemcnttotal').show();
				
				
				if (addareahight > 0) {
			
					if (jQuery("body").hasClass("page-product-grouped")) {
						jQuery('.custom-des-area.expandDiv').css('margin-top',addareahight+48+'px');
					}else{
						jQuery('.custom-des-area.expandDiv').css('margin-top',addareahight+'px');
					}
				}else{
					jQuery('.custom-des-area.expandDiv').css('margin-top',scroll_height-addareahight+'px');
				}
				
				
			}else{
				jQuery('.pdp-main-area-bg').removeClass('fixed-pdp-sticky');
				jQuery('.column.main').removeClass('pdp-sticky-except-area');
				jQuery('div.select-item').hide();
				jQuery('div.stikey_size').hide();
				jQuery('div.stikey_color').hide();
				
				jQuery('span.itemcnt').hide();
				jQuery('span.itemcnttotal').show();
				
				jQuery('.custom-des-area.expandDiv').removeAttr("style");
				
			}
		
		}
	
	});
} 
	});
	 
	 
	
	
	
	// stick PDP end
	
	///////////// new accordian start
	var Accordion = function(el, multiple) {
		this.el = el || {};
		this.multiple = multiple || false;

		// Variables privadas
		var links = this.el.find('label.label-title');
		// Evento
		links.on('click', {el: this.el, multiple: this.multiple}, this.dropdown)
	}
	
	Accordion.prototype.dropdown = function(e) {
			
		e.preventDefault();
		var $el = e.data.el;
			$this = jQuery(this),
			$next = $this.next();
		
		
		var span_first = jQuery(this).find('span:first').text();
		if (span_first.indexOf("1") < 0){
			 jQuery("body, html").animate({ 
			  scrollTop: (jQuery('.customproduct').offset().top)
			});	
		}
			var this_parent = $this.parent();
			
				$el.find('div.control').not($next).slideUp().parent().removeClass('open');
				$next.slideToggle('slow',
				function () {
					if($this.parent().hasClass('open'))
					{
					}
					else
					{
					   $this.parent().addClass('open');
					}
				});
				
	}

	var accordion = new Accordion(jQuery('#product-options-wrapper'), false);
	///////////// new accordian end
		
}); 

function  submitDetailsForm(proid){
jQuery('button.product-from-'+proid).trigger('click');
jQuery('div.product-from-'+proid).find('button').attr('disabled', 'disabled');
jQuery('div.product-from-'+proid).find('span').html('added to bag');

}

</script>
<script type="text/x-magento-init">
        {
            "[data-role=tocart-form1], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
  </script>
  