<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php $_productCollection = $block->getLoadedProductCollection(); ?>
<?php  $_product = $block->getProduct(); ?>

<?php if($_product->getData('product_flag')){
					//echo $product->getData('product_flag');
$pro_flag = $_product->getResource()->getAttribute('product_flag')->getFrontend()->getValue($_product);
$categories = ''; $twoflag = '';
$cats = explode(",", $pro_flag);
$i=1;
foreach($cats as $cat) {
	$cat = trim($cat);
	$categories .= "<span class='flag-".$i."'><img src=".$block->getViewFileUrl('images/'.$cat.'.png').">"  . "</span>\n";
	$i++;
}
echo $categories;

} ?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder" style="opacity:0;">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
        	<img src="<?php echo $block->getGalleryImages()->getFirstItem()->getData('medium_image_url') ?>" style="max-width: 100%; max-height: 100%">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
        </div>
    </div>
</div>

<?php
$images = $_product->getMediaGalleryImages();
$img_cnt = '';
if(count($images)<=1){
$img_cnt = " without-thumb";
} ?>
<div class="pdp-left-icons <?php  echo $img_cnt;?>" >
<ul>
<li><a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><img src='<?php echo $this->getViewFileUrl('images/icon-wishlist.png'); ?>' alt="wishlist" width="23"><span><?php  echo __('Add to favorites')   ?></span></a></li>
 
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "wishlist": {
                    "component": "Magento_Wishlist/js/view/wishlist"
                }
            }
        }
    }
}
</script>
<li><a class="fa-fa-heart" href="#" onClick="window.print()"><img src='<?php echo $this->getViewFileUrl('images/icon-print.png'); ?>' alt="Print" width="20"><span><?php  echo __('Print')   ?></span></a></li>
<li><a class="icon-zoom-in"  href="javascript:void(0);"><img src='<?php echo $this->getViewFileUrl('images/icon-zoom.png'); ?>' alt="Zoom" width="20"><span><?php  echo __('Zoom')   ?></span></a></li>
</ul>
</div>
<!--Fix for jumping content. Loader must be the same size as gallery.-->
<script>
    var config = {
            "width": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
            "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
            "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
            "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height'); ?>
        },
        thumbBarHeight = 0,
        loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

    if (config.navtype === 'horizontal') {
        thumbBarHeight = config.thumbheight;
    }

    loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
</script>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?php /* @escapeNotVerified */ echo $block->getMagnifier(); ?>,
                "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson(); ?>,
                "options": {
                    "nav": "<?php /* @escapeNotVerified */ echo $block->getVar("gallery/nav"); ?>",
                    <?php if (($block->getVar("gallery/loop"))): ?>
                        "loop": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/loop"); ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/keyboard"))): ?>
                        "keyboard": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/keyboard"); ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/arrows"))): ?>
                        "arrows": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/arrows"); ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/allowfullscreen"))): ?>
                        "allowfullscreen": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/allowfullscreen"); ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/caption"))): ?>
                        "showCaption": <?php /* @escapeNotVerified */ echo $block->getVar("gallery/caption"); ?>,
                    <?php endif; ?>
                    "width": "<?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'width'); ?>",
                    "thumbwidth": "<?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'width'); ?>",
                    <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
                        "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                        "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height')
                        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/duration"); ?>,
                    <?php endif; ?>
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/transition/effect"); ?>",
                    <?php if (($block->getVar("gallery/navarrows"))): ?>
                        "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/navarrows"); ?>,
                    <?php endif; ?>
                    "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navtype"); ?>",
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/navdir"); ?>"
                },
                "fullscreen": {
                    "nav": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/nav"); ?>",
                    <?php if ($block->getVar("gallery/fullscreen/loop")): ?>
                        "loop": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/loop"); ?>,
                    <?php endif; ?>
                    "navdir": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navdir"); ?>",
                    <?php if ($block->getVar("gallery/transition/navarrows")): ?>
                        "navarrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navarrows"); ?>,
                    <?php endif; ?>
                    "navtype": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/navtype"); ?>",
                    <?php if ($block->getVar("gallery/fullscreen/arrows")): ?>
                        "arrows": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/arrows"); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/caption")): ?>
                        "showCaption": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/caption"); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/duration"); ?>,
                    <?php endif; ?>
                    "transition": "<?php /* @escapeNotVerified */  echo $block->getVar("gallery/fullscreen/transition/effect"); ?>"
                },
                "breakpoints": <?php /* @escapeNotVerified */ echo $block->getBreakpoints(); ?>
            }
        }
    }
</script>

 <script type="text/javascript">
        require([
        'jquery',
        'fotorama/fotorama',
        'underscore',
        'matchMedia',
        'mage/template',
        'text!mage/gallery/gallery.html',
        'uiClass',
        'mage/translate'
    ], function ($, fotorama, _, mediaCheck, template, galleryTpl, Class, $t) {
        'use strict';


            $("a.icon-zoom-in").on("click" ,function() {       
 
                 var fotorama = $('.fotorama').fotorama({allowfullscreen: true}).data('fotorama');
                 fotorama.requestFullScreen();
                 var $fotoramaDiv = $('.fotorama').fotorama();
                 $fotoramaDiv.data('fotorama').show(0);

            });
	if(jQuery( "div.pdp-main-area" ).length<1){
		jQuery( ".product-info-main" ).wrap( "<div tabindex='0' class='pdp-main-area' ></div>" );
		jQuery( ".pdp-main-area" ).wrap( "<div tabindex='0' class='pdp-main-area-bg' ></div>" );
		jQuery("div.media").detach().insertBefore('div.product-info-main');
	}
});
</script>

<script type="text/javascript">
    require(['jquery', 'mage/gallery/gallery'], function($, gallery){
        $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {
			jQuery('div.fotorama__thumb__arr.fotorama__thumb__arr--left').prependTo( jQuery( "div.fotorama__nav-wrap" ) );
			jQuery('div.fotorama__thumb__arr.fotorama__thumb__arr--right').appendTo( jQuery( "div.fotorama__nav-wrap" ) );
			
			$('div.gallery-placeholder').animate({opacity: 1}, 1000);
			jQuery(window).scrollTop(jQuery(window).scrollTop()+1);
			$(window).scrollTop(jQuery(window).scrollTop()+1);
		});
	jQuery('div.breadcrumbs').show();
	
	
window.onbeforeunload = function () {
  window.scrollTo(0, 0);
}

    });
</script>