<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<!doctype html>
<html <?php /* @escapeNotVerified */ echo $htmlAttributes ?>>
    <head <?php /* @escapeNotVerified */ echo $headAttributes ?>>
        <?php /* @escapeNotVerified */ echo $requireJs ?>
        <?php /* @escapeNotVerified */ echo $headContent ?>
        <?php /* @escapeNotVerified */ echo $headAdditional ?>
    </head>
    <body data-container="body" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?php /* @escapeNotVerified */ echo $loaderIcon; ?>"}}' <?php /* @escapeNotVerified */ echo $bodyAttributes ?>>
    

    <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	
	$variable = $objectManager->create('Magento\Variable\Model\Variable');
	$promo_bar_reset = $variable->loadByCode('promo_bar_reset')->getPlainValue();
	
	?>
    <input type="hidden" id="my_site_base_url" value="<?php  echo $storeManager->getStore()->getBaseUrl(); ?>" />
<div class="spring-roll block-static-block">

    <?php 
	
	//echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_top')->toHtml(); 	
	$block_content = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_top')->toHtml();
	$block_content = str_replace("\n", "", $block_content);
	$block_content = str_replace("\r", "", $block_content);
	
	?></div>
    <script>
    require([
        'jquery',
        'mage/cookies'
    ], function ($) {
       $.cookie('promo_bar_reset', '<?php echo $promo_bar_reset; ?>', { path: '/' });//Set the cookies
    });
</script>

 <script type="text/javascript">
require(['jquery'],function($){

function getCookie(name)
{
var re = new RegExp(name + "=([^;]+)");
var value = re.exec(document.cookie);
return (value != null) ? unescape(value[1]) : null;
}

jQuery(document).on('click', 'a.close', function(){
		$('div.block-static-block').hide();
		var top_stickeyclick = $.cookie("top_stickeyclick");
		
		/*var now = new Date();
		now.setTime(now.getTime() + <?php echo $promo_bar_reset; ?> * 3600 * 1000);*/
		
		 var date = new Date();
		 var minutes = "<?php echo $promo_bar_reset; ?>";
		 date.setTime(date.getTime() + (minutes * 60 * 1000));

		$.cookie('top_stickeyclick', 'yes', { expires:  date , path: '/' });
		
	});
	
	 
   var cookie_val = getCookie("top_stickeyclick");

	 if(cookie_val=='yes'){
			jQuery('div.spring-roll.block-static-block').remove();
		}else{
			var block_content = '<?php echo $block_content; ?>';
			jQuery('div.spring-roll.block-static-block').html(block_content);
		}

});
</script>
<?php         

$cus_pro_dis = $variable->loadByCode('cus_pro_dis')->getPlainValue();
?>
<input type="hidden" name="cus_pro_dis" id="cus_pro_dis" value="<?php echo $cus_pro_dis; ?>" >
		  <?php /* @escapeNotVerified */ echo $layoutContent ?>
    </body>
</html>
