<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('as-seen-in-content1')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('as-seen-in-quote')->toHtml(); ?>
<div class="asseein-three">
<div class="asseein-three-in">
<div class="magazine-title as_comn"><h2>In the Press</h2></div>
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('mageplaza_betterslider_banner'); //gives table name with prefix
 
/*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $variable = $objectManager->create('Magento\Variable\Model\Variable');

    $value = $variable->loadByCode('as_seen_in_meta_description')->getHtmlValue();
    echo $value;
//Select Data from table

$sql_update_status = "update " . $tableName." set `url` = 2";
$connection->query($sql_update_status);
*/
$sql = "Select * FROM " . $tableName."  WHERE `status` = '1' ORDER BY `url` ASC";

$result = $connection->fetchAll($sql);
//var_dump($result);

$media_path = '';


if (strpos($this->getBaseUrl(), '192.168.1.151/jaysonhome') !== false) {
	$media_path = '/pub';
}else{
	$media_path = '';
}
?>
<div class="magazines_main">
<?php

foreach($result as $_result){
if($_result['type'] == 1){
?>
<div class="magagines">
<a href="<?php echo $this->getUrl('as-seen-in/in-the-press').'#'.'featured-'.$_result['banner_id'];?>"><img src="<?php echo $this->getBaseUrl().$media_path."/media/mageplaza/betterslider/banner/image".$_result['upload_file']; ?>" /></a>
</div>
<?php
}
}
 
?>
</div>

<div class="ass-view-all"><a href="<?php echo $this->getUrl('as-seen-in/in-the-press') ?>"><span class="cta-btn-text">VIEW ALL</span> <span class="cta-btn-icon">&nbsp;</span></a></div>
</div>
</div>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('as-seen-in-store-spotlight')->toHtml(); ?>

<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('as-seen-in-social-media')->toHtml(); ?>

<?php //echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('asseenas-video-journal')->toHtml(); ?>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $("body").addClass("asseenas-index-index");
    });
</script>